// Английский словарь для хаба. Ключ - русская исходная строка (см. i18n.ts).
// Если строки нет в словаре, t() вернёт русский ключ (безопасный фолбэк).
export const EN: Record<string, string> = {
  // ── Навигация / вкладки ──────────────────────────────────────────────
  'Дом': 'Home',
  'Магазин': 'Shop',
  'Аватар': 'Avatar',
  'Друзья': 'Friends',
  'Профиль': 'Profile',
  'Звук': 'Sound',
  'Помощь': 'Help',
  'Магазин стиля': 'Style shop',
  'Хаб': 'Hub',

  // ── Загрузка / общие ─────────────────────────────────────────────────
  'Открываем игровую…': 'Opening the arcade…',
  'Загрузка магазина…': 'Loading the shop…',
  'Загрузка профиля…': 'Loading profile…',
  'Загрузка стиля…': 'Loading style…',
  'Загрузка коллекций…': 'Loading collections…',
  'Загрузка барахолки…': 'Loading the market…',
  'Загрузка рейтингов…': 'Loading leaderboards…',
  'Загрузка сезона…': 'Loading the season…',
  'Открываем витрину…': 'Opening the showcase…',
  'Открываем гардероб…': 'Opening the wardrobe…',
  'Событие завершилось.': 'The event has ended.',
  'Понятно': 'Got it',
  'Закрыть': 'Close',
  'Выйти': 'Leave',
  'Предмет': 'Item',
  'нет': 'none',
  'Игрок': 'Player',
  'забрать': 'claim',
  'Куплено': 'Owned',

  // ── App: листы About/Help/Settings ──────────────────────────────────
  'Game is Game': 'Game is Game',
  'Все наши игры в одном месте': 'All our games in one place',
  'Один аккаунт, все наши игры. Открываешь хаб, выбираешь игру, и она запускается сразу. Друзья, уровни и значки общие для всех игр.':
    'One account, all our games. Open the hub, pick a game, and it launches instantly. Friends, levels and badges are shared across every game.',
  'Как это работает': 'How it works',
  'Выбери игру в «Доме», она откроется сразу. Добавляй друзей по коду, соревнуйся в «Ленте» и качай уровень за запуски игр.':
    'Pick a game on the Home tab and it opens right away. Add friends by code, compete in the Feed, and level up by playing games.',
  'открыть хаб': 'open the hub',
  'список игр': 'list of games',
  'помощь': 'help',
  'Настройки': 'Settings',
  'Тихие щелчки в интерфейсе': 'Quiet clicks in the interface',
  'Об этом приложении': 'About this app',
  'Что такое Game is Game': 'What Game is Game is',
  'Как пользоваться хабом': 'How to use the hub',
  'Сделано с любовью ♥': 'Made with love ♥',
  'Язык': 'Language',
  'Русский или English': 'Russian or English',

  // ── Профиль-редактор ─────────────────────────────────────────────────
  'Ник': 'Username',
  'Ник берётся из твоего Telegram и общий для всех наших игр.':
    'Your username comes from Telegram and is shared across all our games.',
  'Придумай ник': 'Pick a username',
  'ник': 'username',
  'В Telegram у тебя нет @username, поэтому выбери свой, 3-32 символа: латиница, цифры и «_». Его больше никто не сможет занять.':
    "You don't have a Telegram @username, so pick your own: 3–32 characters, Latin letters, digits and “_”. No one else will be able to take it.",
  'Закрепить ник': 'Lock in username',
  'Сменить образ': 'Change look',
  'Ник: 3-32 символа, латиница, цифры и _': 'Username: 3–32 characters, Latin letters, digits and _',
  'Этот ник уже занят, придумай другой': 'That username is taken, pick another',
  'Ник уже закреплён': 'Username already locked',
  'Недопустимый ник': 'Invalid username',

  // ── Коллекции ────────────────────────────────────────────────────────
  'Коллекции': 'Collections',
  'Собери все предметы коллекции и получи бонус Game.': 'Collect every item in a collection to earn a Game bonus.',

  // ── Команды / кланы ──────────────────────────────────────────────────
  'участников': 'members',
  'лидер': 'leader',
  'участник': 'member',
  'Общая цель недели': 'Weekly team goal',
  'Состав': 'Roster',
  'Топ команд': 'Top teams',
  'Команды': 'Teams',
  'Собери команду, бейте общие цели и поднимайтесь в топе.':
    'Build a team, hit shared goals and climb the rankings together.',
  'Создать команду': 'Create a team',
  'Название': 'Name',
  'ТЕГ': 'TAG',
  'Создать': 'Create',
  'Найти команду': 'Find a team',
  'Пока команд нет, создай первую!': 'No teams yet - create the first one!',
  'Вступить': 'Join',

  // ── Барахолка / рынок ────────────────────────────────────────────────
  'Барахолка': 'Market',
  'Выставить свой образ': 'List your item',
  'Нет торгуемых образов. Купи что-нибудь в магазине.': 'No tradeable items. Buy something in the shop first.',
  'Выбери образ…': 'Pick an item…',
  'Цена': 'Price',
  'Продать': 'Sell',
  'Мои лоты': 'My listings',
  'Снять': 'Cancel',
  'Лоты игроков': 'Player listings',
  'Пока пусто': "It's empty here",
  'Загляни позже, тут появятся образы игроков.': 'Check back later - player items will show up here.',
  'Купить': 'Buy',

  // ── Рейтинги ─────────────────────────────────────────────────────────
  'Рейтинги': 'Leaderboards',
  'GG-лига': 'GG League',
  'Неделя': 'Week',
  'Играй и зарабатывай, рейтинг наполнится.': 'Play and earn - the leaderboard will fill up.',
  'Бронза': 'Bronze',
  'Серебро': 'Silver',
  'Золото': 'Gold',
  'Платина': 'Platinum',
  'Алмаз': 'Diamond',
  'Мастер': 'Master',
  'Грандмастер': 'Grandmaster',

  // ── Событие / фестиваль ──────────────────────────────────────────────
  'Общая цель': 'Community goal',
  'Задания события': 'Event quests',
  'Магазин события': 'Event shop',

  // ── Сезонный пропуск ─────────────────────────────────────────────────
  'Бесплатно': 'Free',
  'Награды сезона': 'Season rewards',
  'Премиум': 'Premium',
  'максимум': 'maxed',
  'дальше:': 'next:',
  'Пропуск пройден 🏆': 'Pass completed 🏆',
  'Премиум активен ✨': 'Premium active ✨',
  'все награды премиум-трека': 'all premium-track rewards',
  'Пропуск+ 🔥': 'Pass+ 🔥',
  'мгновенно продвинуться по пропуску': 'jump ahead on the pass instantly',
  'получено': 'claimed',
  'Моя GG-лига:': 'My GG League:',

  // ── Home ─────────────────────────────────────────────────────────────
  'Найти игру…': 'Find a game…',
  'Поиск по играм': 'Search games',
  'Очистить': 'Clear',
  'Все': 'All',
  'Избранное': 'Favorites',
  'Друзья в сети 🟢': 'Friends online 🟢',
  'в сети': 'online',
  'Продолжить': 'Continue',
  'Популярное': 'Popular',
  'Снова в деле': 'Back in action',
  'Начни здесь': 'Start here',
  'Играть': 'Play',
  'Найдено': 'Found',
  'Все игры': 'All games',
  'Игры от игроков': 'Player-made games',
  'Сделано в Мастерской': 'Made in the Workshop',
  'от': 'by',
  'В избранном пусто': 'No favorites yet',
  'Ничего не нашлось': 'Nothing found',
  'Отмечай игры звёздочкой, и они соберутся здесь.': 'Star games and they will gather here.',
  'Попробуй другое название или сними фильтры.': 'Try another name or clear the filters.',
  'Недавнее': 'Recent',
  'Убрать из избранного': 'Remove from favorites',
  'В избранное': 'Add to favorite',
  'Задания дня': 'Daily quests',
  'новые каждый день': 'new every day',
  'Задания недели': 'Weekly quests',
  'сброс в понедельник': 'resets Monday',
  'Игра недели': 'Game of the week',
  'Открыть →': 'Open →',
  'осталось': 'left',
  'Пропуск': 'Pass',
  'тир': 'tier',
  'Тир': 'Tier',
  'Уровень': 'Level',
  'Ур.': 'Lvl',

  // ── Карточка игры ────────────────────────────────────────────────────
  'Одиночная': 'Solo',
  'С друзьями': 'With friends',
  'Один и с друзьями': 'Solo & with friends',
  'запуск': 'launch',
  'запусков': 'launches',
  'в игре': 'in game',
  'Оцени первым': 'Be the first to rate',
  'Нравится': 'Like',
  'Не очень': 'Not great',
  'В избранном': 'Favorited',
  'Слежу': 'Following',
  'Следить': 'Follow',
  'Поделиться с друзьями': 'Share with friends',
  'Секрет': 'Secret',
  'Скрытое достижение: открой, чтобы узнать': 'Hidden achievement: unlock to reveal',
  'Максимум взят': 'Maxed out',
  'редкое': 'rare',

  // ── Задания / квесты ─────────────────────────────────────────────────
  'Заменить задание': 'Reroll quest',
  'замена: 1 бесплатно': 'reroll: 1 free',

  // ── Профиль ──────────────────────────────────────────────────────────
  'Серия': 'Streak',
  'Друзей': 'Friends',
  'рек.': 'best',
  'дней': 'days',
  'порвалась, восстанови за 24 ч!': 'broke - restore it within 24h!',
  '▶ 3 игры даром': '▶ 3 games free',
  'Игры': 'Games',
  'Престиж: сбросить уровень за звезду': 'Prestige: reset your level for a star',
  'Статистика игр': 'Game stats',
  'Значки': 'Badges',
  'Достижения': 'Achievements',
  'По играм': 'By game',
  'игр': 'games',
  'КОД ДРУГА': 'FRIEND CODE',
  'Код скопирован ✨': 'Code copied ✨',
  'Редактировать имя': 'Edit name',

  // ── Друзья ───────────────────────────────────────────────────────────
  'Лидеры': 'Leaders',
  'Лента': 'Feed',
  'Зови друзей, получай Game': 'Invite friends, earn Game',
  'Пригласить друга': 'Invite a friend',
  'Дружеские серии 🔥🤝': 'Friend streaks 🔥🤝',
  'играйте в один день': 'play on the same day',
  'Кооп-квесты 🤝': 'Co-op quests 🤝',
  'вместе с другом': 'together with a friend',
  'Твой код друга': 'Your friend code',
  'Копировать': 'Copy',
  'Поделиться': 'Share',
  'Добавить друга': 'Add a friend',
  'Код, напр. K7M2QX': 'Code, e.g. K7M2QX',
  'Добавить': 'Add',
  'Команда': 'Team',
  'Мои друзья': 'My friends',
  'Пока никого': 'No one yet',
  'Поделись кодом или добавь друга, и играйте вместе.': 'Share your code or add a friend, and play together.',
  'Глобальные рейтинги': 'Global leaderboards',
  'Таблица пустеет': 'The board is empty',
  'Добавь друзей и запускай игры. Появится рейтинг по опыту.':
    'Add friends and play games. A leaderboard by XP will appear.',
  'Тихо пока': 'Quiet for now',
  'Когда ты или друзья запускаете игры, события появятся здесь.':
    'When you or your friends play games, events will show up here.',
  'Подарить Game': 'Gift Game',
  'до 3 в день': 'up to 3 a day',
  'Или подари предмет': 'Or gift an item',
  'Дарить можно только покупные вещи, заслуги остаются с тобой.':
    'You can only gift purchased items - earned rewards stay with you.',
  'Не хватает Game': 'Not enough Game',
  'Лимит: 5 подарков в день': 'Limit: 5 gifts a day',
  'Вы не в друзьях': "You're not friends",
  'От 10 до 1000 Game': 'From 10 to 1000 Game',
  'Код не найден': 'Code not found',
  'Это твой код 🙂': "That's your own code 🙂",
  'Уже в друзьях': 'Already friends',
  'Не получилось': "That didn't work",
  'У друга уже есть этот предмет': 'Your friend already has this item',
  'Лимит подарков-предметов на сегодня': "Item-gift limit reached for today",
  'Не получилось подарить предмет': "Couldn't gift the item",
  'Не получилось отправить': "Couldn't send",
  'добавлен 🎉': 'added 🎉',
  'Приглашено:': 'Invited:',
  'Заработано:': 'Earned:',
  'пни 👉': 'nudge 👉',
  '✓ награда забрана': '✓ reward claimed',
  'играет в': 'playing',
  'был(а)': 'seen',
  'давно не заходил(а)': "hasn't been around",
  'Бросить вызов:': 'Challenge:',
  'Кооп-квест:': 'Co-op quest:',
  'Подарить Game:': 'Gift Game:',
  'Удалить из друзей': 'Remove friend',
  'ты': 'you',
  'открыл(а)': 'opened',
  'игру': 'a game',
  'Подарок отправлен:': 'Gift sent:',
  'обрадуется 🎁': 'will be delighted 🎁',

  // ── Магазин ──────────────────────────────────────────────────────────
  'Магазин стиля ': 'Style shop',
  'Зарабатывай Game в играх и собирай редкие образы': 'Earn Game in games and collect rare looks',
  'Витрина дня': 'Daily showcase',
  'новое каждый день': 'new every day',
  'уходит скоро': 'leaving soon',
  'Коллекции ': 'Collections',
  'Косметика': 'Cosmetics',
  'Всё': 'All',
  'Здесь пусто': "It's empty here",
  'В этой категории пока нет товаров.': 'No items in this category yet.',
  'Пополнить баланс': 'Top up balance',
  'за Telegram Stars': 'with Telegram Stars',
  '×2 первая': '×2 first buy',
  'Скоро': 'Soon',
  'Уже куплено, надень во вкладке «Аватар»': 'Already owned - equip it on the Avatar tab',
  'Скоро в продаже ✨': 'Coming soon ✨',
  'Не хватает Game 💰': 'Not enough Game 💰',

  // ── Стиль / аватар ───────────────────────────────────────────────────
  'Не хватает Game 💰, загляни в Магазин': 'Not enough Game 💰 - check the Shop',
  'Этот предмет закрыт 🔒': 'This item is locked 🔒',
  'Перекрасить тело': 'Recolor body',
  'сброс бесплатно': 'reset is free',
  'оригинал': 'original',
  'оттенок': 'hue',
  'Откроется:': 'Unlocks at:',

  // ── Слоты косметики ──────────────────────────────────────────────────
  'Цвет': 'Color',
  'Лицо': 'Face',
  'Рамка': 'Frame',
  'Шляпа': 'Hat',
  'Очки': 'Eyewear',
  'Эффект': 'Effect',
  'Питомец': 'Pet',
  'Баннер': 'Banner',
  'Титул': 'Title',

  // ── Редкости ─────────────────────────────────────────────────────────
  'Обычная': 'Common',
  'Редкая': 'Rare',
  'Эпическая': 'Epic',
  'Легендарная': 'Legendary',
  'Мифическая': 'Mythic',

  // ── Категории игр ────────────────────────────────────────────────────
  'Карты': 'Cards',
  'Настольные': 'Board',
  'Компания': 'Party',
  'Слова': 'Words',
  'Аркады': 'Arcade',
  'Головоломки': 'Puzzle',
  'Стратегии': 'Strategy',

  // ── Тосты store.ts ───────────────────────────────────────────────────
  'Друг': 'Friend',
  'пригласил(а) тебя! Сыграй 5 игр и получишь': 'invited you! Play 5 games and get',
  'Вызов принят:': 'Challenge accepted:',
  'теперь в друзьях 🎉': 'is now your friend 🎉',
  'Задание выполнено:': 'Quest complete:',
  'Уровень сброшен, вперёд по новой!': 'Level reset - off you go again!',
  'Серия восстановлена 🔧🔥': 'Streak restored 🔧🔥',
  'Награда получена:': 'Reward claimed:',
  'Коллекция собрана:': 'Collection complete:',
  'создана 🛡️': 'created 🛡️',
  'Ты в команде': "You're in the team",
  'Награда события:': 'Event reward:',
  'куплено 🎉': 'purchased 🎉',
  'закреплён ✨': 'locked in ✨',
  'Награда уже получена': 'Reward already claimed',
  'Задание ещё не выполнено': 'Quest not finished yet',
  'Задание заменено': 'Quest rerolled',
  'Не удалось заменить': "Couldn't reroll",
  'Не хватает Game на реролл': 'Not enough Game to reroll',
  'Оплата прошла: Game уже на балансе 🎉': 'Payment complete: Game added to your balance 🎉',
  'Пополнение работает внутри Telegram': 'Top-up works inside Telegram',
  'Не получилось открыть счёт': "Couldn't open the invoice",
  'Друг получил напоминание 🔥🤝': 'Your friend got a nudge 🔥🤝',
  'Уже напоминал(а) сегодня': 'Already nudged today',
  'Кооп-квест начат 🤝 Играйте вместе!': 'Co-op quest started 🤝 Play together!',
  'Сначала добавь в друзья': 'Add them as a friend first',
  'Не удалось начать': "Couldn't start",
  'Кооп-награда получена 🤝': 'Co-op reward claimed 🤝',
  'Цель ещё не достигнута': 'Goal not reached yet',
  'Не удалось': "That didn't work",
  'Не удалось обновить избранное': "Couldn't update favorites",
  'Подпишем на новости этой игры 🔔': "You'll get news about this game 🔔",
  'Не удалось обновить подписку': "Couldn't update your follow",
  'Не удалось сохранить оценку': "Couldn't save your rating",
  'Престиж откроется на 100 уровне': 'Prestige unlocks at level 100',
  'Не хватает Game на ремонт': 'Not enough Game for a repair',
  'Сыграй 3 матча для бесплатного ремонта': 'Play 3 matches for a free repair',
  'Окно ремонта закрыто': 'The repair window has closed',
  'заморозка': 'freeze',
  'предмет': 'item',
  'Нужен премиум-пропуск': 'Premium pass required',
  'Тир ещё не открыт': 'Tier not unlocked yet',
  'Премиум-пропуск активирован ✨': 'Premium pass activated ✨',
  'Покупка пропуска работает внутри Telegram': 'Buying the pass works inside Telegram',
  'Лот выставлен 🏷️': 'Listing posted 🏷️',
  'Сыграй больше игр, чтобы торговать': 'Play more games to trade',
  'Цена вне допустимых границ': 'Price is out of range',
  'Лимит лотов на сегодня': "Listing limit reached for today",
  'Не удалось выставить': "Couldn't post the listing",
  'Куплено на барахолке 🎉': 'Bought on the market 🎉',
  'Лот уже продан': 'Listing already sold',
  'Не удалось купить': "Couldn't buy",
  'Лот снят': 'Listing removed',
  'Не удалось снять лот': "Couldn't remove the listing",
  'Уже получено': 'Already claimed',
  'Коллекция ещё не собрана': 'Collection not complete yet',
  'Такой тег занят': 'That tag is taken',
  'Ты уже в команде': "You're already in a team",
  'Проверь название и тег': 'Check the name and tag',
  'В команде нет мест': 'The team is full',
  'Не удалось вступить': "Couldn't join",
  'Ты покинул(а) команду': 'You left the team',
  'Награда команды получена 🎉': 'Team reward claimed 🎉',
  'Награда сообщества получена 🎉': 'Community reward claimed 🎉',
  'Куплено за 🎟': 'Bought with 🎟',
  'Не хватает 🎟': 'Not enough 🎟',
  'Этот предмет ещё закрыт': 'This item is still locked',
  'Не удалось надеть': "Couldn't equip",
  'Не хватает Game на перекраску': 'Not enough Game to recolor',
  'Не удалось перекрасить': "Couldn't recolor",
  'Покупка не удалась': 'Purchase failed',

  // ── Динамические фрагменты Home ──────────────────────────────────────
  'Открыть': 'Open',
  'Открыть аватар': 'Open avatar',
  'играет · зайти': 'playing · join',
  'в': 'in',
  'зайти': 'join',
  'можно забрать:': 'claimable:',
  'дн.': 'd.',
  'забрать:': 'claim:',
  'Престиж': 'Prestige',
  'Идеальная серия': 'Perfect streak',

  // ── Каталог игр: названия ────────────────────────────────────────────
  'Маньяк': 'Maniac',
  'Нитро-лига': 'Nitro League',
  'Неон-Тайд': 'Neon Tide',
  'Чехарда': 'Leapfrog',
  'Однушечка': 'Wildcard',
  'Крокоша': 'Charades',
  'Секрет ночи': 'Night Secret',
  'Сакс-будильник': 'Sax Alarm',
  'Шарик': 'Buddy',
  'Картишки': 'Bad Cards',
  'Слабо?': 'Dare?',
  'Викторина': 'Quiz',
  'Крот': 'The Mole',
  'Домино': 'Dominoes',
  'Лото': 'Bingo',
  'Лесенки': 'Snakes & Ladders',
  'Магнат': 'Tycoon',
  'Гнездо': 'Roost',
  'Тропа войны': 'Warpath',
  'Морской бой': 'Battleship',
  'Маджонг': 'Mahjong',
  'Реверси': 'Reversi',
  'Паук': 'Spider',
  'Виселица': 'Hangman',
  'Буквица': 'Word Board',
  'Плетёнка': 'Word Weave',
  'Хрумик': 'Muncher',
  'Пузырик': 'Bubbles',
  'Шайбус': 'Air Hockey',
  'Дуплет': '8-Ball',
  'Рикошет': 'Ricochet',
  'Танчики': 'Tanks',
  'Забава': 'Fun Pack',
  'Клеточки': 'Nonograms',
  'Кубик': 'Cube',
  'Линик': 'Lines',
  'Складик': 'Sokoban',
  'Четыре в ряд': 'Four in a Row',
  'Го': 'Go',
  'Сёги': 'Shogi',
  'Сянци': 'Xiangqi',
  'Легион': 'Legion',
  'Натиск': 'Onslaught',

  // ── Каталог игр: подписи (tagline) ───────────────────────────────────
  'Голубиная почта по живой карте мира': 'Pigeon post across a living world map',
  '3D-Risk: захвати весь мир': '3D Risk: conquer the whole world',
  '3D детектив: вычисли убийцу': '3D whodunit: find the killer',
  '3D ракетный футбол на тачках': '3D rocket car football',
  '3D лодка из блоков против реки ловушек': '3D block boat vs. a river of traps',
  '3D шоу на вылет за короной': '3D knockout show for the crown',
  'Карты по цвету и числу': 'Match cards by color and number',
  'Показывай и угадывай слова': 'Act out and guess words',
  'Тайные роли, блеф и интуиция': 'Secret roles, bluffing and intuition',
  'Саксофоны будят, дринк спасает': 'Saxes wake you, a sip saves you',
  'Питомец, о котором заботишься': 'A pet you look after',
  'Карточная игра с чёрным юмором': 'A card game with dark humor',
  'Правда или действие': 'Truth or dare',
  'Вопросы и ответы для компании': 'Trivia questions for the group',
  'Вычисли предателя в компании': 'Spot the impostor in the group',
  'Классика за деревянным столом': 'A classic at the wooden table',
  'Классика на 90 бочонков': 'The classic 90-barrel game',
  'Кубик, змейки и лесенки': 'Dice, snakes and ladders',
  'Скупай улицы, строй империю': 'Buy up streets, build an empire',
  'Найди и потопи флот 10x10': 'Find and sink the fleet on 10×10',
  'Разбирай доску парами фишек': 'Clear the board matching pairs',
  'Переворачивай фишки соперника': "Flip your opponent's pieces",
  'Пасьянс: собери все масти': 'Solitaire: collect every suit',
  'Угадай слово по буквам': 'Guess the word letter by letter',
  'Составляй слова на доске': 'Build words on the board',
  'Найди слова в сетке букв': 'Find words in a grid of letters',
  'Съешь всё и убеги от призраков': 'Eat it all and flee the ghosts',
  'Лопай шарики по три': 'Pop bubbles in threes',
  'Аэрохоккей: первый до семи': 'Air hockey: first to seven',
  'Бильярд: восьмёрка в лузу': 'Pool: sink the 8-ball',
  'Ракетка, мяч и кирпичи': 'Paddle, ball and bricks',
  'Танковый бой с волнами врагов': 'Tank battle against enemy waves',
  'Три мини-игры под одной крышей': 'Three mini-games under one roof',
  'Японские кроссворды': 'Japanese picture crosswords',
  'Собери кубик Рубика на время': "Solve the Rubik's cube on the clock",
  'Собирай линии из шариков': 'Line up balls in a row',
  'Растолкай ящики по местам': 'Push crates into place',
  'Собери линию из четырёх': 'Line up four in a row',
  'Окружай территорию на доске': 'Surround territory on the board',
  'Японские шахматы': 'Japanese chess',
  'Китайские шахматы': 'Chinese chess',
  'Захвати мир боями на кубиках': 'Conquer the world with dice battles',
  'Стратегия захвата карты': 'A map-conquest strategy game',

  // ── Каталог игр: описания (blurb) ────────────────────────────────────
  'Отправляй настоящие письма виртуальными голубями: птица летит по карте мира в реальном времени, скорость зависит от вида и расстояния. Собирай птиц, выводи яйца, гоняй во Флаппи.':
    'Send real letters by virtual pigeons: the bird flies across the world map in real time, its speed depends on species and distance. Collect birds, hatch eggs, race in Flappy.',
  'Настольный Риск в 3D: 42 территории на карте мира, живые кубики на физике, бонусы за континенты. Соло против ботов трёх уровней сложности или передавай телефон друзьям.':
    'Tabletop Risk in 3D: 42 territories on the world map, live physics dice, continent bonuses. Solo against bots on three difficulty levels or pass the phone to friends.',
  'Настольная монополия в 3D: покупай улицы, строй дома и отели, разоряй соперников. Играй с ботами или друзьями онлайн.':
    'Tabletop Monopoly in 3D: buy streets, build houses and hotels, bankrupt your rivals. Play against bots or with friends online.',
  'Социальная 3D-дедукция: один тайный Маньяк с ножом, один Шериф с единственным патроном, остальные выживают и вычисляют, кто есть кто. Соло с ботами или с друзьями по коду комнаты.':
    'Social 3D deduction: one secret Maniac with a knife, one Sheriff with a single bullet, everyone else survives and works out who is who. Solo with bots or with friends by room code.',
  'Реактивные тачки играют в футбол: буст, сальто и голы. Матч против бота или 1×1 с другом по коду комнаты.':
    'Jet-powered cars play football: boost, flips and goals. Match a bot or 1v1 a friend by room code.',
  'Строй лодку из дерева, металла и золота, запускай по неоновой реке сквозь пилы, пушки и водопад, забирай сундук с золотом. Соло или с друзьями по коду комнаты.':
    'Build a boat from wood, metal and gold, sail it down a neon river through saws, cannons and a waterfall, and grab the chest of gold. Solo or with friends by room code.',
  'Безумная 3D полоса препятствий: шестнадцать зефирок, три раунда на вылет, одна корона.':
    'A wild 3D obstacle course: sixteen marshmallows, three knockout rounds, one crown.',
  'Весёлая карточная игра про цвета и числа, в духе «Уно».':
    'A fun card game about colors and numbers, in the spirit of Uno.',
  'Игра в ассоциации, цифровой «Крокодил»: угадывай слова по подсказкам.':
    'A word-association game, digital Charades: guess words from clues.',
  'Социальная игра про доверие и обман, в духе «Мафии».':
    'A social game of trust and deception, in the spirit of Mafia.',
  'Социальный «будильник»: саксофоны нарастают, пока не докажешь глоток на камеру. Сквады, множители и лидерборд.':
    'A social “alarm clock”: the saxophones build up until you prove a sip on camera. Squads, multipliers and a leaderboard.',
  'Тёплая игра про питомца, немного как тамагочи: заботишься о зверьке, а заодно и о себе.':
    'A cozy pet game, a little like a Tamagotchi: care for the critter and for yourself along the way.',
  'Партийная карточная игра для компании: подбирай самый смешной ответ на вопрос раунда.':
    'A party card game for the group: pick the funniest answer to the round’s question.',
  'Классика вечеринок: отвечай честно или выполняй задание, три набора на любую компанию.':
    'A party classic: answer honestly or take the dare - three decks for any crowd.',
  'Соревнование эрудитов: пять тем, быстрые раунды, играй один или с друзьями.':
    'A battle of wits: five topics, fast rounds - play solo or with friends.',
  'Социальная игра: у всех одно слово, у крота другое. Вычисли, кто прикидывается.':
    'A social game: everyone shares one word, the mole has another. Work out who’s faking.',
  'Классическое домино: выкладывай кости, блокируй соперника, считай очки.':
    'Classic dominoes: lay tiles, block your opponent, count the points.',
  'Русское лото: закрывай числа на карточках, пока ведущий тянет бочонки.':
    'Russian lotto: mark the numbers on your cards as the host draws the barrels.',
  'Настольная классика: бросай кубик, лезь по лесенкам и не съезжай по змейкам.':
    'A board classic: roll the die, climb the ladders and dodge the snakes.',
  'Настольная игра про недвижимость: покупай улицы, строй дома и разоряй соперников.':
    'A real-estate board game: buy streets, build houses and bankrupt your rivals.',
  'Классический морской бой: расставь корабли и первым разгадай расстановку соперника.':
    'Classic Battleship: place your ships and be first to crack your opponent’s layout.',
  'Классический пасьянс-маджонг: снимай парные фишки и разбирай всю доску.':
    'Classic Mahjong solitaire: remove matching tiles and clear the whole board.',
  'Классика стратегии: зажимай фишки соперника и перекрашивай доску в свой цвет.':
    'A strategy classic: trap your opponent’s pieces and flip the board to your color.',
  'Классический пасьянс «Паук»: раскладывай колонны по порядку и собирай масти.':
    'Classic Spider solitaire: order the columns and build up the suits.',
  'Классическая игра в слова: открывай буквы и угадай слово раньше, чем кончатся попытки.':
    'A classic word game: reveal letters and guess the word before you run out of tries.',
  'Игра в слова на доске 15x15: выкладывай буквы, зарабатывай очки за редкие клетки.':
    'A word game on a 15×15 board: place letters and score big on rare squares.',
  'Филворд: слова спрятаны в сетке и переплетены как нитки, найди их все.':
    'A word search: words hide in the grid, woven like threads - find them all.',
  'Неоновая аркада про обжорку в лабиринте: собирай точки и уворачивайся от призраков.':
    'A neon arcade muncher in a maze: gobble the dots and dodge the ghosts.',
  'Bubble shooter: стреляй шариками, собирай тройки по цвету и очищай поле.':
    'A bubble shooter: fire bubbles, match threes by color and clear the field.',
  'Глянцевый аэрохоккей с честной физикой: отбивай шайбу и забивай до семи голов.':
    'Glossy air hockey with fair physics: knock the puck and score up to seven goals.',
  'Бильярдная «восьмёрка» с честной физикой: забей свои шары и восьмёрку последней.':
    '8-ball pool with fair physics: pot your balls, then sink the 8-ball last.',
  'Неоновая аркада: отбивай мяч ракеткой и выбивай кирпичи рикошетами.':
    'A neon arcade: bounce the ball off your paddle and smash the bricks.',
  'Аркада про танковый бой: защищай базу и отбивай волны вражеских танков.':
    'A tank-battle arcade: defend your base and fend off waves of enemy tanks.',
  'Сборник мини-игр: память, точки и спираль. Короткие партии на пару минут.':
    'A mini-game collection: memory, dots and spiral. Quick rounds of a couple minutes.',
  'Нонограммы: открывай клетки по числам и собирай картинку.':
    'Nonograms: reveal cells by the numbers and uncover the picture.',
  'Головоломка про кубик 3x3: крути грани и собери все цвета быстрее всех.':
    'A 3×3 cube puzzle: turn the faces and match every color as fast as you can.',
  'Головоломка «Lines»: двигай шарики и собирай линии по пять, пока поле не заполнилось.':
    'The Lines puzzle: move balls and form lines of five before the board fills up.',
  'Сокобан: толкай ящики на нужные места, не загнав их в угол.':
    'Sokoban: push crates onto their targets without cornering them.',
  'Логическая классика на двоих: бросай фишки в колонны и собери четыре в ряд.':
    'A two-player logic classic: drop discs into columns and get four in a row.',
  'Древняя игра Го: окружай территорию и камни соперника на доске 9x9.':
    'The ancient game of Go: surround territory and enemy stones on a 9×9 board.',
  'Японские шахматы: съеденные фигуры возвращаются в бой на твоей стороне.':
    'Japanese chess: captured pieces return to the fight on your side.',
  'Китайские шахматы: генералы, пушки и река посреди доски.':
    'Chinese chess: generals, cannons and a river across the middle of the board.',
  'Стратегия про захват мира: двигай легионы, бросай кубики и держи континенты.':
    'A world-conquest strategy: move legions, roll dice and hold the continents.',
  'Настольная стратегия: расширяй владения и выдавливай соперников с карты.':
    'A board strategy game: expand your holdings and squeeze rivals off the map.',

  // -- Задания и фестивали (auto-added) --
  '23 Февраля': 'February 23',
  '8 Марта': 'March 8',
  'День Победы': 'Victory Day',
  'Добавь игру в избранное': 'Add a game to favorites',
  'Заходи 5 дней из 7': 'Visit 5 of 7 days',
  'Летний движ': 'Summer Vibes',
  'Масленица': 'Maslenitsa',
  'Новый год': 'New Year',
  'Открой 2 разные игры': 'Open 2 different games',
  'Открой 3 разные игры': 'Open 3 different games',
  'Открой 5 разных игр': 'Open 5 different games',
  'Открой 7 разных игр': 'Open 7 different games',
  'Оцени 3 игры': 'Rate 3 games',
  'Оцени 5 игр': 'Rate 5 games',
  'Оцени любую игру': 'Rate any game',
  'Поиграй в 3 разных жанра': 'Play 3 different genres',
  'Сообщество: 100 000 партий на Хэллоуин': 'Community: 100,000 rounds for Halloween',
  'Сообщество: 120 000 партий к 23 февраля': 'Community: 120,000 rounds by February 23',
  'Сообщество: 120 000 партий к 8 марта': 'Community: 120,000 rounds by March 8',
  'Сообщество: 120 000 партий на Масленицу': 'Community: 120,000 rounds for Maslenitsa',
  'Сообщество: 150 000 партий к 9 мая': 'Community: 150,000 rounds by May 9',
  'Сообщество: 200 000 партий за праздники': 'Community: 200,000 rounds for the holidays',
  'Сообщество: 50 000 запусков за лето': 'Community: 50,000 plays over the summer',
  'Сыграй 10 раз': 'Play 10 times',
  'Сыграй 13 раз': 'Play 13 times',
  'Сыграй 20 партий за неделю': 'Play 20 rounds this week',
  'Сыграй 20 раз за праздники': 'Play 20 times over the holidays',
  'Сыграй 9 раз': 'Play 9 times',
  'Сыграй в 3 игры': 'Play 3 games',
  'Сыграй в жанре «Аркады»': 'Play an Arcade game',
  'Сыграй в жанре «Головоломки»': 'Play a Puzzle game',
  'Сыграй в жанре «Карты»': 'Play a Cards game',
  'Сыграй в жанре «Компания»': 'Play a Party game',
  'Сыграй в жанре «Настольные»': 'Play a Board game',
  'Сыграй в жанре «Слова»': 'Play a Words game',
  'Сыграй в жанре «Стратегии»': 'Play a Strategy game',
  'Хэллоуин': 'Halloween',
  // -- Косметика (auto-added) --
  '3D-очки': '3D Glasses',
  'Аврора': 'Aurora',
  'Аква': 'Aqua',
  'Амбассадор': 'Ambassador',
  'Аметист': 'Amethyst',
  'Армия': 'Army',
  'Багрянец': 'Crimson',
  'Базовые': 'Basic',
  'Бантик': 'Bow',
  'Барвинок': 'Periwinkle',
  'Без очков': 'No eyewear',
  'Без питомца': 'No pet',
  'Без рамки': 'No frame',
  'Без шляпы': 'No hat',
  'Без эффекта': 'No effect',
  'Бездна': 'Abyss',
  'Берет': 'Beret',
  'Бессмертный': 'Immortal',
  'Бирюза': 'Turquoise',
  'Блинный': 'Pancake',
  'Блины': 'Pancakes',
  'Бриллиант': 'Diamond',
  'В команде': 'On the Team',
  'Везунчик': 'Lucky One',
  'Венец': 'Crown',
  'Весенний': 'Springtime',
  'Влюблён': 'In Love',
  'Вулкан': 'Volcano',
  'Выпускник': 'Graduate',
  'Высший свет': 'High Society',
  'ГОАТ': 'GOAT',
  'Галактика': 'Galaxy',
  'Гвардия': 'Guard',
  'Гик': 'Geek',
  'Глитч': 'Glitch',
  'Глубокие': 'Deep',
  'Гогглы': 'Goggles',
  'Гранат': 'Garnet',
  'Графит': 'Graphite',
  'Гриб': 'Mushroom',
  'Гроза': 'Storm',
  'Грозный': 'Fierce',
  'Гуру': 'Guru',
  'Гуру игр': 'Game Guru',
  'Дед Мороз хаба': 'Hub Santa',
  'Динозаврик': 'Dino',
  'Дракончик': 'Dragon',
  'Дрон': 'Drone',
  'Дух хаба': 'Hub Spirit',
  'Душа весны': 'Soul of Spring',
  'Душа компании': 'Life of the Party',
  'Единорожек': 'Unicorn',
  'Жуть': 'Spooky',
  'За достижение': 'For an Achievement',
  'Заводила': 'Ringleader',
  'Задира': 'Bully',
  'Закат': 'Sunset',
  'Заслуги': 'Merits',
  'Защитник': 'Defender',
  'Звёздные глаза': 'Starry Eyes',
  'Звёздные очки': 'Star Shades',
  'Звёздочка': 'Little Star',
  'Звёзды': 'Stars',
  'Знамя': 'Banner',
  'Идея': 'Idea',
  'Изумруд': 'Emerald',
  'Индиго': 'Indigo',
  'Инопланетянин': 'Alien',
  'Ирис': 'Iris',
  'Искры': 'Sparkles',
  'Исследователь': 'Explorer',
  'Капюшон': 'Hood',
  'Карамель': 'Candy',
  'Кармин': 'Carmine',
  'Каска': 'Hard Hat',
  'Каталог': 'Catalogue',
  'Кепка': 'Cap',
  'Кибер': 'Cyber',
  'Кит': 'Whale',
  'Кобальт': 'Cobalt',
  'Ковбойская': 'Cowboy Hat',
  'Коллекционер': 'Collector',
  'Колпак': 'Party Hat',
  'Колпак Санты': 'Santa Hat',
  'Колпак мага': 'Wizard Hat',
  'Комбо-кинг': 'Combo King',
  'Конфедератка': 'Grad Cap',
  'Конфетти': 'Confetti',
  'Коралл': 'Coral',
  'Король карт': 'Card King',
  'Корона': 'Crown',
  'Космос': 'Cosmos',
  'Котёнок': 'Kitten',
  'Крем': 'Cream',
  'Крем-брюле': 'Creme Brulee',
  'Кружится': 'Dizzy',
  'Крутыш': 'Cool',
  'Лава': 'Lava',
  'Лаванда': 'Lavender',
  'Лайм': 'Lime',
  'Легенда GG': 'GG Legend',
  'Легенда двора': 'Yard Legend',
  'Легенда хаба': 'Hub Legend',
  'Лес': 'Forest',
  'Летний': 'Summery',
  'Лето': 'Summer',
  'Листья': 'Leaves',
  'Лисёнок': 'Fox',
  'Лёд': 'Ice',
  'Магия': 'Magic',
  'Малахит': 'Malachite',
  'Малая корона': 'Coronet',
  'Мандарин': 'Tangerine',
  'Маска': 'Mask',
  'Маска театра': 'Theatre Mask',
  'Маскировка': 'Disguise',
  'Масло': 'Butter',
  'Мастер блефа': 'Bluff Master',
  'Матрица': 'Matrix',
  'Милашка': 'Cutie',
  'Милое': 'Cute',
  'Мимоза': 'Mimosa',
  'Мифические': 'Mythic',
  'Мифический': 'Mythic',
  'Мозг': 'Brain',
  'Молнии': 'Lightning',
  'Монокль': 'Monocle',
  'Море': 'Sea',
  'Морозко': 'Frosty',
  'Мох': 'Moss',
  'Мята': 'Mint',
  'На страже хаба': 'Guarding the Hub',
  'Небеса': 'Heavens',
  'Небо': 'Sky',
  'Небожитель': 'Celestial',
  'Незабудка': 'Forget-me-not',
  'Неон': 'Neon',
  'Нимб': 'Halo',
  'Новичок': 'Rookie',
  'Новобранец': 'Recruit',
  'Ночная сова': 'Night Owl',
  'Обсидиан': 'Obsidian',
  'Огонь': 'Fire',
  'Огонь-30': 'Streak 30',
  'Океан': 'Ocean',
  'Основатель': 'Founder',
  'Палитра': 'Palette',
  'Пандочка': 'Panda',
  'Персик': 'Peach',
  'Пиксель': 'Pixel',
  'Пилотка': 'Cap',
  'Питомцы': 'Pets',
  'Пламя': 'Flame',
  'Победитель': 'Winner',
  'Подмигивание': 'Wink',
  'Полночь': 'Midnight',
  'Полуночник': 'Night Owl',
  'Помним': 'We Remember',
  'Праздник': 'Party',
  'Преданный': 'Devoted',
  'Привидение': 'Ghost',
  'Природа': 'Nature',
  'Про': 'Pro',
  'Пропеллер': 'Propeller',
  'Птенчик': 'Chick',
  'Пудра': 'Powder',
  'Пузыри': 'Bubbles',
  'Пчёлка': 'Bee',
  'Радость': 'Joy',
  'Радуга': 'Rainbow',
  'Ретро': 'Retro',
  'Ретровейв': 'Retrowave',
  'Рог': 'Horn',
  'Рожки': 'Horns',
  'Роза': 'Rose',
  'Розовое золото': 'Rose Gold',
  'Роскошь': 'Luxury',
  'Рубин': 'Ruby',
  'Рупор': 'Megaphone',
  'Сакура': 'Sakura',
  'Сапфир': 'Sapphire',
  'Свитчер': 'Switcher',
  'Сезон': 'Season',
  'Сезонный пропуск': 'Season Pass',
  'Сердечки': 'Hearts',
  'Сияние': 'Radiance',
  'Снег': 'Snow',
  'Снежинка': 'Snowflake',
  'Снежный': 'Snowy',
  'Снэпбэк': 'Snapback',
  'Событие': 'Event',
  'События': 'Events',
  'Совёнок': 'Owl',
  'Сонный': 'Sleepy',
  'Соучастник': 'Accomplice',
  'Спидранер': 'Speedrunner',
  'Спорт': 'Sport',
  'Стиль': 'Style',
  'Стихии': 'Elements',
  'Стратег': 'Strategist',
  'Стройка': 'Construction',
  'Сцена': 'Stage',
  'Тактик': 'Tactician',
  'Терракота': 'Terracotta',
  'Товарищ': 'Comrade',
  'Топ': 'Top',
  'Туманность': 'Nebula',
  'Тыква-шлем': 'Pumpkin Helm',
  'Тыквенный': 'Pumpkin',
  'Тьма': 'Darkness',
  'Тёмная аура': 'Dark Aura',
  'Тёмные очки': 'Shades',
  'Уборы': 'Headwear',
  'Уголёк': 'Ember',
  'Удивление': 'Surprise',
  'Уличное': 'Street',
  'Улыбка': 'Smile',
  'Ультрамарин': 'Ultramarine',
  'Универсал': 'All-Rounder',
  'Учёба': 'School',
  'Фартовый': 'Jammy',
  'Феникс': 'Phoenix',
  'Фиолет': 'Violet',
  'Фуксия': 'Fuchsia',
  'Хитрец': 'Sly One',
  'Хранитель Шарика': 'Keeper of Sharik',
  'Цветок': 'Flower',
  'Цилиндр': 'Top Hat',
  'Чаща': 'Thicket',
  'Чемпион': 'Champion',
  'Чемпион района': 'District Champion',
  'Черепашка': 'Turtle',
  'Чёрное золото': 'Black Gold',
  'Шалфей': 'Sage',
  'Широкая душа': 'Big Heart',
  'Шлем космонавта': 'Astronaut Helmet',
  'Шляпка': 'Sun Hat',
  'Шпион': 'Spy',
  'Щенок': 'Puppy',
  'Электрик': 'Electric Blue',
  'Электро': 'Electro',
  'Эмоции': 'Emotions',
  'Янтарь': 'Amber',
  'Яркие': 'Bright',
  // -- Достижения (auto-added) --
  'Арахнолог': 'Arachnologist',
  'Аркадный ас': 'Arcade Ace',
  'Без отмен': 'No Undos',
  'Без ошибок': 'Flawless',
  'Без падений': 'No Falls',
  'Безупречно': 'Flawless',
  'Бери короны': 'Claim Crowns',
  'Блицкриг': 'Blitzkrieg',
  'Богач': 'Rich',
  'Боец': 'Fighter',
  'Бомбардир': 'Striker',
  'Боцман': 'Bosun',
  'Верни к жизни запущенного питомца': 'Bring a neglected pet back to life',
  'Верный хозяин': 'Loyal Owner',
  'Ветеран': 'Veteran',
  'Ветеран трассы': 'Track Veteran',
  'Виртуоз': 'Virtuoso',
  'Воздушный ас': 'Aerial Ace',
  'Возьми первую корону в «Чехарде»': 'Win your first crown in «Frogfall»',
  'Возьми финальный раунд быстрее порога': 'Win the final round under the time limit',
  'Всухую': 'Shutout',
  'Второе дыхание': 'Second Wind',
  'Выбей целый ряд одним рикошетом': 'Clear a whole row with one ricochet',
  'Выживший': 'Survivor',
  'Выиграй первый матч в «Маньяке»': 'Win your first match in «Maniac»',
  'Выиграй первый матч в «Нитро-лиге»': 'Win your first match in «Nitro League»',
  'Выиграй по очкам в наглухо заблокированной партии': 'Win on points in a fully blocked game',
  'Выиграй ранговый матч, будучи в низшем дивизионе': 'Win a ranked match while in the lowest division',
  'Выиграй раунд ведущим': 'Win a round as the host',
  'Выиграй эпизод, ни разу не упав': 'Win an episode without falling once',
  'Выиграй, не пропустив ни одного гола': 'Win without conceding a single goal',
  'Выиграй, уступая 2+ гола': 'Win while trailing by 2+ goals',
  'Выполни задание «действие» на камеру': 'Complete a «dare» task on camera',
  'Вычисли крота с первого голосования': 'Spot the mole on the first vote',
  'Гардеробщик': 'Wardrobe Keeper',
  'Год в GG': 'A Year in GG',
  'Голеадор': 'Goal Machine',
  'Головолом': 'Puzzler',
  'Гроза лобби': 'Lobby Terror',
  'Гроссмейстер': 'Grandmaster',
  'Гроссмейстер очков': 'Score Grandmaster',
  'Гурман': 'Gourmet',
  'Дари монеты друзьям': 'Gift coins to friends',
  'Даритель': 'Giver',
  'Две недели': 'Two Weeks',
  'Двойная угроза': 'Double Threat',
  'Дебют': 'Debut',
  'Дегустатор': 'Taster',
  'Дедукция': 'Deduction',
  'Дежавю': 'Deja Vu',
  'Дерби': 'Derby',
  'Держи питомца ухоженным неделю подряд': 'Keep your pet groomed for a week straight',
  'Держи серию дней подряд': 'Keep a daily streak going',
  'Десяток': 'Ten Down',
  'Доберись до сундука, не потеряв ни одного блока': 'Reach the chest without losing a single block',
  'Добряк': 'Kind Soul',
  'Доведи все показатели питомца до максимума': 'Max out all of your pet\'s stats',
  'Доживи до конца матча 10 раз': 'Survive to the end of a match 10 times',
  'Дойди до третьего раунда 10 раз': 'Reach the third round 10 times',
  'Дойди до финиша, не съехав ни по одной змее': 'Reach the finish without sliding down a single snake',
  'Достигни максимальной привязанности': 'Reach maximum bond',
  'Друзья-соперники': 'Frenemies',
  'Душа хаба': 'Heart of the Hub',
  'Живучий': 'Survivor',
  'За Маньяка победи после публичного обвинения': 'As the Maniac, win after being publicly accused',
  'За Шерифа потрать единственный патрон точно в Маньяка': 'As the Sheriff, land your only bullet on the Maniac',
  'За мирного подай решающий голос, изгоняющий Маньяка': 'As a townsperson, cast the deciding vote to banish the Maniac',
  'Забей 3+ гола за один матч': 'Score 3+ goals in a single match',
  'Забей все свои шары и восьмёрку без промаха': 'Pot all your balls and the 8-ball without a miss',
  'Забей гол с лёта, в воздухе': 'Score a goal on the volley, mid-air',
  'Забивай голы': 'Score goals',
  'Забирай золотой сундук': 'Grab the gold chest',
  'Заботливый': 'Caring',
  'Заботься о питомце': 'Take care of your pet',
  'Заверши заплыв быстрее порога': 'Finish a run under the time limit',
  'Заверши заплыв вместе с другом': 'Finish a run together with a friend',
  'Заверши заплыв на золотых блоках': 'Finish a run on gold blocks',
  'Заверши заплывы': 'Finish runs',
  'Заверши первый заплыв в «Неон-Тайде»': 'Finish your first run in «Neon Tide»',
  'Заводи друзей в хабе': 'Make friends in the hub',
  'Завсегдатай': 'Regular',
  'Зазывала': 'Recruiter',
  'Заклятые друзья': 'Sworn Frenemies',
  'Закрой карточку раньше всех «по кону»': 'Close your card before everyone else «on the pot»',
  'Захвати карту за минимум ходов': 'Take the map in the fewest moves',
  'Звезда лиги': 'League Star',
  'Здоровяк': 'Picture of Health',
  'Зефирная молния': 'Marshmallow Lightning',
  'Змеелов': 'Snake Charmer',
  'Знаток': 'Connoisseur',
  'Знаток каталога': 'Catalog Connoisseur',
  'Знаток режимов': 'Mode Master',
  'Золотой флот': 'Golden Fleet',
  'Играй в «Маньяка»': 'Play «Maniac»',
  'Играй в «Неон-Тайд»': 'Play «Neon Tide»',
  'Играй в «Нитро-лигу»': 'Play «Nitro League»',
  'Играй в «Чехарду»': 'Play «Frogfall»',
  'Играй в РАЗНЫЕ игры несколько дней подряд': 'Play DIFFERENT games several days in a row',
  'Из грязи в князи': 'Rags to Riches',
  'Из тупика': 'Out of the Dead End',
  'Инженер': 'Engineer',
  'Камбэк': 'Comeback',
  'Капитан': 'Captain',
  'Каскад': 'Cascade',
  'Клуб 100': 'Club 100',
  'Коллекционер трофеев': 'Trophy Collector',
  'Коллекция': 'Collection',
  'Комбо-брейкер': 'Combo Breaker',
  'Компанейский': 'Sociable',
  'Континент': 'Continent',
  'Контрразведка': 'Counterintelligence',
  'Кооп': 'Co-op',
  'Копилка': 'Piggy Bank',
  'Король шоу': 'Show King',
  'Кошмар города': 'Town Nightmare',
  'Крепость': 'Fortress',
  'Крёстный отец': 'Godfather',
  'Кто здесь Маньяк': 'Who\'s the Maniac',
  'Кутюрье': 'Couturier',
  'Легенда': 'Legend',
  'Легенда пасьянса': 'Solitaire Legend',
  'Легенда реки': 'River Legend',
  'Легенда роста': 'Growth Legend',
  'Лучший друг': 'Best Friend',
  'Любящий': 'Loving',
  'Магнат реки': 'River Tycoon',
  'Магнат стиля': 'Style Tycoon',
  'Марафон разнообразия': 'Variety Marathon',
  'Марафонец': 'Marathoner',
  'Мастер Маньяка': 'Maniac Master',
  'Мастер Неон-Тайда': 'Neon Tide Master',
  'Мастер Нитро': 'Nitro Master',
  'Мастер Паука': 'Spider Master',
  'Мастер Чехарды': 'Frogfall Master',
  'Мастер Шарика': 'Sharik Master',
  'Мастер мастеров': 'Master of Masters',
  'Мастер на все руки': 'Jack of All Trades',
  'Мастер раскладов': 'Layout Master',
  'Мастерство': 'Skill',
  'Мат в миттельшпиле': 'Mate in the Middlegame',
  'Месяц': 'A Month',
  'Месяц без повторов': 'A Month, No Repeats',
  'Мета': 'Meta',
  'Меткий шериф': 'Sharpshooter Sheriff',
  'Меценат': 'Patron',
  'Меценат друзей': 'Friends\' Patron',
  'Модник': 'Trendsetter',
  'Молния': 'Lightning',
  'Монополист': 'Monopolist',
  'На разогреве': 'Warming Up',
  'Набирай очки достижений (GG Score)': 'Earn achievement points (GG Score)',
  'Найди все слова, не ошибившись': 'Find all the words without a mistake',
  'Накорми питомца всеми видами еды': 'Feed your pet every type of food',
  'Народный чемпион': 'People\'s Champion',
  'Настольный гений': 'Tabletop Genius',
  'Не один': 'Not Alone',
  'Не пропусти ни дня': 'Don\'t Miss a Day',
  'Неделя разнообразия': 'Variety Week',
  'Непоседа': 'Fidget',
  'Неубиваемый': 'Unkillable',
  'Новичок славы': 'Rising Rookie',
  'Ночной город': 'Night City',
  'Обжора': 'Glutton',
  'Общество': 'Social',
  'Обыграй друга в РАЗНЫХ играх (§7A ⑱)': 'Beat a friend in DIFFERENT games (§7A ⑧)',
  'Обыграй живого соперника': 'Beat a live opponent',
  'Обыгрывай живых соперников (не ботов)': 'Beat live opponents (not bots)',
  'Одним из первых заверши сезонный пропуск': 'Be among the first to finish the season pass',
  'Одним махом': 'One Fell Swoop',
  'Оптимист': 'Optimist',
  'Открой все достижения «Маньяка»': 'Unlock all «Maniac» achievements',
  'Открой все достижения «Неон-Тайда»': 'Unlock all «Neon Tide» achievements',
  'Открой все достижения «Нитро-лиги»': 'Unlock all «Nitro League» achievements',
  'Открой все достижения «Паука»': 'Unlock all «Spider» achievements',
  'Открой все достижения «Чехарды»': 'Unlock all «Frogfall» achievements',
  'Открой все достижения «Шарика»': 'Unlock all «Sharik» achievements',
  'Открывай достижения': 'Unlock achievements',
  'Открытия': 'Exploration',
  'Охотник': 'Hunter',
  'Охотник за трофеями': 'Trophy Hunter',
  'Панчлайн': 'Punchline',
  'Пасьянсник': 'Solitaire Player',
  'Паучок': 'Little Spider',
  'Первая кровь': 'First Blood',
  'Первая победа': 'First Win',
  'Первопроходец': 'Pioneer',
  'Первопроходец сезона': 'Season Pioneer',
  'Первый гол': 'First Goal',
  'Первый друг': 'First Friend',
  'Первый пасьянс': 'First Solitaire',
  'Переживи секцию водопада': 'Survive the waterfall section',
  'Платиновый охотник': 'Platinum Hunter',
  'Победи быстрее порога времени': 'Win under the time limit',
  'Победи в играх всех 7 жанров за один день': 'Win games in all 7 genres in a single day',
  'Победи в компании из 6+ человек': 'Win in a group of 6+ people',
  'Победи в матче с 6+ живыми игроками': 'Win a match with 6+ live players',
  'Победи в полном лобби из 16 игроков': 'Win a full 16-player lobby',
  'Победи в экспресс-темпе': 'Win at express pace',
  'Победи во всех трёх мини-играх подряд': 'Win all three mini-games in a row',
  'Победи за Маньяка, не собрав против себя ни одного голоса': 'Win as the Maniac without drawing a single vote',
  'Победи за Мафию, оставшись до конца': 'Win as the Mafia, surviving to the end',
  'Победи за минимум ходов': 'Win in the fewest moves',
  'Победи из явно проигрышной позиции': 'Win from a clearly losing position',
  'Победи менее чем за 25 ходов': 'Win in under 25 moves',
  'Победи с идеальным раундом': 'Win with a perfect round',
  'Победи с перевесом в 50+ очков': 'Win by a margin of 50+ points',
  'Победи со счётом 7:0': 'Win 7:0',
  'Победи, будучи последним в начале третьего раунда': 'Win after being last at the start of the third round',
  'Победи, владея полным набором цвета с отелями': 'Win owning a full color set with hotels',
  'Победи, заняв 50+ клеток': 'Win by taking 50+ cells',
  'Победи, не набрав ни одного штрафного очка': 'Win without taking a single penalty point',
  'Победи, не получив ни одного урона': 'Win without taking any damage',
  'Победи, не потеряв ни одной фигуры': 'Win without losing a single piece',
  'Победи, не сделав ни одной ошибки': 'Win without making a single mistake',
  'Победи, скинув последней картой «+4»': 'Win by playing «+4» as your last card',
  'Победи, создав вилку из двух угроз': 'Win by creating a fork of two threats',
  'Победитель людей': 'Human Beater',
  'Побеждай в «Маньяке»': 'Win in «Maniac»',
  'Побеждай в «Нитро-лиге»': 'Win in «Nitro League»',
  'Побеждай в матчах по всему каталогу': 'Win matches across the catalog',
  'Побеждай в разных жанрах': 'Win across different genres',
  'Покупатель': 'Shopper',
  'Полимат': 'Polymath',
  'Полный дом': 'Full House',
  'Полный лоббик': 'Full Lobby',
  'Полный стол': 'Full Table',
  'Популярный': 'Popular',
  'Потопи весь флот, потратив ≤25 выстрелов': 'Sink the whole fleet using ≤25 shots',
  'Преданность': 'Dedication',
  'Прерви серию из 5+ побед другого игрока': 'Break another player\'s 5+ win streak',
  'Приглашай новых игроков': 'Invite new players',
  'Проведи первый день с питомцем': 'Spend your first day with a pet',
  'Проводи дни с питомцем': 'Spend days with your pet',
  'Прогресс': 'Progress',
  'Проиграй одной игре 3 раза подряд, и всё-таки победи': 'Lose the same game 3 times in a row, then win anyway',
  'Пройди волну, не потеряв базу': 'Clear a wave without losing your base',
  'Пройди раунд без единой ошибки': 'Clear a round without a single mistake',
  'Против людей': 'Vs. Humans',
  'Проходи первый раунд': 'Clear the first round',
  'Прошёл всё': 'Played Them All',
  'Пять жанров': 'Five Genres',
  'Пятёрка': 'Five in a Row',
  'Разбери всю доску без застреваний': 'Clear the whole board without getting stuck',
  'Разбери доску без отмен': 'Clear the board without undos',
  'Разгром': 'Blowout',
  'Разминка': 'Warm-up',
  'Раскладчик': 'Dealer',
  'Раскладывай «Паука»': 'Play «Spider»',
  'Речной волк': 'River Wolf',
  'Реши без подсказок и отмен': 'Solve without hints or undos',
  'Реши быстрее порога времени': 'Solve under the time limit',
  'Реши нонограмму без единой ошибки': 'Solve a nonogram without a single mistake',
  'Реши уровень за минимум ходов': 'Solve a level in the fewest moves',
  'Родная душа': 'Soulmate',
  'Рыба': 'Blocked Out',
  'С первой буквы': 'First Letter',
  'Сарафан': 'Word of Mouth',
  'Семь на семь': 'Seven for Seven',
  'Серийный': 'Serial',
  'Серийный чемпион': 'Serial Champion',
  'Скопи 25 000 Game на балансе (и потрать же!)': 'Save up 25,000 Game in your balance (and spend it!)',
  'Скоростной': 'Speedy',
  'Скороход': 'Speedrunner',
  'Словесник': 'Wordsmith',
  'Слово дня': 'Word of the Day',
  'Смельчак': 'Daredevil',
  'Снайпер': 'Sniper',
  'Собери кубик быстрее порога': 'Solve the cube under the time limit',
  'Собери линию из 5 шаров одним ходом': 'Line up 5 balls in a single move',
  'Собери пасьянс быстрее порога': 'Complete a solitaire under the time limit',
  'Собери пасьянс из почти безвыходного расклада': 'Complete a solitaire from a near-hopeless deal',
  'Собери пасьянс, ни разу не отменив ход': 'Complete a solitaire without a single undo',
  'Собери первый пасьянс в «Пауке»': 'Complete your first solitaire in «Spider»',
  'Собери расклад в две масти': 'Complete a two-suit deal',
  'Собери расклад в четыре масти': 'Complete a four-suit deal',
  'Собери слово из 7 букв на бонусной клетке': 'Make a 7-letter word on a bonus tile',
  'Собирай косметику': 'Collect cosmetics',
  'Собирай пасьянсы': 'Complete solitaires',
  'Сова': 'Night Owl',
  'Спидкубер': 'Speedcuber',
  'Спуск на воду': 'Launch',
  'Становись «Мастером» в разных играх': 'Become a «Master» in different games',
  'Стиляга': 'Stylish',
  'Сухая победа': 'Clean Sheet',
  'Схлопни 10+ шаров одним выстрелом': 'Pop 10+ balls with a single shot',
  'Съешь всю доску и 4 призраков за один буст': 'Eat the whole board and 4 ghosts in one boost',
  'Сыграй в 10 разных игр за один день': 'Play 10 different games in a single day',
  'Сыграй в разные игры каталога': 'Play different games from the catalog',
  'Сыграй ночью, с 03:00 до 05:00 МСК': 'Play at night, between 03:00 and 05:00 MSK',
  'Сыграй с питомцем во все мини-игры': 'Play every mini-game with your pet',
  'Телепат': 'Telepath',
  'Территория': 'Territory',
  'Транжира': 'Spendthrift',
  'Трать монеты в магазине': 'Spend coins in the shop',
  'Три дня': 'Three Days',
  'Три жанра': 'Three Genres',
  'Три из трёх': 'Three for Three',
  'Троих обыграл': 'Beat Three',
  'Угадай с первых попыток': 'Guess on the first tries',
  'Угадай слово меньше чем за 10 секунд': 'Guess the word in under 10 seconds',
  'Угадай слово, не сделав ни одной ошибки': 'Guess the word without a single mistake',
  'Удержи целый континент до своего хода': 'Hold a whole continent until your turn',
  'Филолог': 'Philologist',
  'Финалист': 'Finalist',
  'Хет-трик': 'Hat-trick',
  'Хищник': 'Predator',
  'Хладнокровный': 'Cold-blooded',
  'Хозяин': 'Owner',
  'Целым и невредимым': 'Safe and Sound',
  'Центурион': 'Centurion',
  'Чемпион категорий': 'Category Champion',
  'Чистая рука': 'Clean Hand',
  'Чистое поле': 'Clean Board',
  'Чистый прогон': 'Clean Run',
  'Чистюля': 'Neat Freak',
  'Шулер': 'Card Shark',
  'Щедрый': 'Generous',
  'Экономика': 'Economy',
  'Энциклопедист': 'Encyclopedist',
  'Эрудит': 'Scholar',
  'Эрудит-мастер': 'Master Scholar',
  'Юнга': 'Cabin Boy',

  // -- Игры (auto-added) --
  'Найтлайн': 'Nightline',
  '3D ночной рынок от первого лица': 'A first-person 3D night market',
  'Неоновый ночной рынок: ходи по докам от первого лица, делай забросы, дерись с машинами охраны и торгуй на живой бирже. Демо: деньги ненастоящие.': 'A neon night market: roam the docks in first person, make drops, fight security cars and trade on a live exchange. Demo: the money is fake.',

  // -- Прогрессия/вехи (auto-added) --
  'Поехали': 'Let’s go',
  'Первый запуск игры': 'First game launched',
  'Сыграно 2 разные игры': 'Played 2 different games',
  'Все четыре': 'All four',
  'Попробованы все игры': 'Tried every game',
  '10 запусков игр': '10 game launches',
  '50 запусков игр': '50 game launches',
  'Добавлен первый друг': 'First friend added',
  '5 друзей в хабе': '5 friends in the hub',
  '5 уровень': 'Level 5',
  'Достигнут 5 уровень': 'Reached level 5',
  'Первый друг пришёл по твоей ссылке': 'First friend joined via your link',
  '5 друзей пришли по твоей ссылке': '5 friends joined via your link',
  // -- Достижения по играм/жанрам (auto-added) --
  'Соверши фирменный приём игры «Маньяк»': 'Pull off the signature move in “Maniac”',
  'Впервые пройди матч в «Маньяк»': 'Win your first match in “Maniac”',
  'Играй в «Маньяк»': 'Play “Maniac”',
  'Побеждай в «Маньяк»': 'Win in “Maniac”',
  'Обыгрывай живых соперников в «Маньяк»': 'Beat live opponents in “Maniac”',
  'Сыграй во всех режимах «Маньяк»': 'Play all modes of “Maniac”',
  'Мастер: Маньяк': 'Master: Maniac',
  'Открой все достижения «Маньяк»': 'Unlock all achievements in “Maniac”',
  'Мастер «Маньяк»': 'Master of “Maniac”',
  'Соверши фирменный приём игры «Нитро-лига»': 'Pull off the signature move in “Nitro League”',
  'Впервые пройди матч в «Нитро-лига»': 'Win your first match in “Nitro League”',
  'Играй в «Нитро-лига»': 'Play “Nitro League”',
  'Побеждай в «Нитро-лига»': 'Win in “Nitro League”',
  'Обыгрывай живых соперников в «Нитро-лига»': 'Beat live opponents in “Nitro League”',
  'Сыграй во всех режимах «Нитро-лига»': 'Play all modes of “Nitro League”',
  'Мастер: Нитро-лига': 'Master: Nitro League',
  'Открой все достижения «Нитро-лига»': 'Unlock all achievements in “Nitro League”',
  'Мастер «Нитро-лига»': 'Master of “Nitro League”',
  'Соверши фирменный приём игры «Найтлайн»': 'Pull off the signature move in “Nightline”',
  'Впервые пройди матч в «Найтлайн»': 'Win your first match in “Nightline”',
  'Играй в «Найтлайн»': 'Play “Nightline”',
  'Побеждай в «Найтлайн»': 'Win in “Nightline”',
  'Обыгрывай живых соперников в «Найтлайн»': 'Beat live opponents in “Nightline”',
  'Сыграй во всех режимах «Найтлайн»': 'Play all modes of “Nightline”',
  'Мастер: Найтлайн': 'Master: Nightline',
  'Открой все достижения «Найтлайн»': 'Unlock all achievements in “Nightline”',
  'Мастер «Найтлайн»': 'Master of “Nightline”',
  'Соверши фирменный приём игры «Неон-Тайд»': 'Pull off the signature move in “Neon Tide”',
  'Впервые пройди матч в «Неон-Тайд»': 'Win your first match in “Neon Tide”',
  'Побеждай в «Неон-Тайд»': 'Win in “Neon Tide”',
  'Обыгрывай живых соперников в «Неон-Тайд»': 'Beat live opponents in “Neon Tide”',
  'Сыграй во всех режимах «Неон-Тайд»': 'Play all modes of “Neon Tide”',
  'Мастер: Неон-Тайд': 'Master: Neon Tide',
  'Открой все достижения «Неон-Тайд»': 'Unlock all achievements in “Neon Tide”',
  'Мастер «Неон-Тайд»': 'Master of “Neon Tide”',
  'Соверши фирменный приём игры «Чехарда»': 'Pull off the signature move in “Leapfrog”',
  'Впервые пройди матч в «Чехарда»': 'Win your first match in “Leapfrog”',
  'Играй в «Чехарда»': 'Play “Leapfrog”',
  'Побеждай в «Чехарда»': 'Win in “Leapfrog”',
  'Обыгрывай живых соперников в «Чехарда»': 'Beat live opponents in “Leapfrog”',
  'Сыграй во всех режимах «Чехарда»': 'Play all modes of “Leapfrog”',
  'Мастер: Чехарда': 'Master: Leapfrog',
  'Открой все достижения «Чехарда»': 'Unlock all achievements in “Leapfrog”',
  'Мастер «Чехарда»': 'Master of “Leapfrog”',
  'Соверши фирменный приём игры «Однушечка»': 'Pull off the signature move in “Wildcard”',
  'Впервые пройди матч в «Однушечка»': 'Win your first match in “Wildcard”',
  'Играй в «Однушечка»': 'Play “Wildcard”',
  'Побеждай в «Однушечка»': 'Win in “Wildcard”',
  'Обыгрывай живых соперников в «Однушечка»': 'Beat live opponents in “Wildcard”',
  'Сыграй во всех режимах «Однушечка»': 'Play all modes of “Wildcard”',
  'Мастер: Однушечка': 'Master: Wildcard',
  'Открой все достижения «Однушечка»': 'Unlock all achievements in “Wildcard”',
  'Мастер «Однушечка»': 'Master of “Wildcard”',
  'Соверши фирменный приём игры «Крокоша»': 'Pull off the signature move in “Charades”',
  'Впервые пройди матч в «Крокоша»': 'Win your first match in “Charades”',
  'Играй в «Крокоша»': 'Play “Charades”',
  'Побеждай в «Крокоша»': 'Win in “Charades”',
  'Обыгрывай живых соперников в «Крокоша»': 'Beat live opponents in “Charades”',
  'Сыграй во всех режимах «Крокоша»': 'Play all modes of “Charades”',
  'Мастер: Крокоша': 'Master: Charades',
  'Открой все достижения «Крокоша»': 'Unlock all achievements in “Charades”',
  'Мастер «Крокоша»': 'Master of “Charades”',
  'Соверши фирменный приём игры «Секрет ночи»': 'Pull off the signature move in “Night Secret”',
  'Впервые пройди матч в «Секрет ночи»': 'Win your first match in “Night Secret”',
  'Играй в «Секрет ночи»': 'Play “Night Secret”',
  'Побеждай в «Секрет ночи»': 'Win in “Night Secret”',
  'Обыгрывай живых соперников в «Секрет ночи»': 'Beat live opponents in “Night Secret”',
  'Сыграй во всех режимах «Секрет ночи»': 'Play all modes of “Night Secret”',
  'Мастер: Секрет ночи': 'Master: Night Secret',
  'Открой все достижения «Секрет ночи»': 'Unlock all achievements in “Night Secret”',
  'Мастер «Секрет ночи»': 'Master of “Night Secret”',
  'Соверши фирменный приём игры «Сакс-будильник»': 'Pull off the signature move in “Sax Alarm”',
  'Впервые пройди матч в «Сакс-будильник»': 'Win your first match in “Sax Alarm”',
  'Играй в «Сакс-будильник»': 'Play “Sax Alarm”',
  'Побеждай в «Сакс-будильник»': 'Win in “Sax Alarm”',
  'Обыгрывай живых соперников в «Сакс-будильник»': 'Beat live opponents in “Sax Alarm”',
  'Сыграй во всех режимах «Сакс-будильник»': 'Play all modes of “Sax Alarm”',
  'Мастер: Сакс-будильник': 'Master: Sax Alarm',
  'Открой все достижения «Сакс-будильник»': 'Unlock all achievements in “Sax Alarm”',
  'Мастер «Сакс-будильник»': 'Master of “Sax Alarm”',
  'Соверши фирменный приём игры «Шарик»': 'Pull off the signature move in “Buddy”',
  'Впервые пройди матч в «Шарик»': 'Win your first match in “Buddy”',
  'Играй в «Шарик»': 'Play “Buddy”',
  'Побеждай в «Шарик»': 'Win in “Buddy”',
  'Обыгрывай живых соперников в «Шарик»': 'Beat live opponents in “Buddy”',
  'Сыграй во всех режимах «Шарик»': 'Play all modes of “Buddy”',
  'Мастер: Шарик': 'Master: Buddy',
  'Открой все достижения «Шарик»': 'Unlock all achievements in “Buddy”',
  'Мастер «Шарик»': 'Master of “Buddy”',
  'Соверши фирменный приём игры «Картишки»': 'Pull off the signature move in “Bad Cards”',
  'Впервые пройди матч в «Картишки»': 'Win your first match in “Bad Cards”',
  'Играй в «Картишки»': 'Play “Bad Cards”',
  'Побеждай в «Картишки»': 'Win in “Bad Cards”',
  'Обыгрывай живых соперников в «Картишки»': 'Beat live opponents in “Bad Cards”',
  'Сыграй во всех режимах «Картишки»': 'Play all modes of “Bad Cards”',
  'Мастер: Картишки': 'Master: Bad Cards',
  'Открой все достижения «Картишки»': 'Unlock all achievements in “Bad Cards”',
  'Мастер «Картишки»': 'Master of “Bad Cards”',
  'Соверши фирменный приём игры «Слабо?»': 'Pull off the signature move in “Dare?”',
  'Впервые пройди матч в «Слабо?»': 'Win your first match in “Dare?”',
  'Играй в «Слабо?»': 'Play “Dare?”',
  'Побеждай в «Слабо?»': 'Win in “Dare?”',
  'Обыгрывай живых соперников в «Слабо?»': 'Beat live opponents in “Dare?”',
  'Сыграй во всех режимах «Слабо?»': 'Play all modes of “Dare?”',
  'Мастер: Слабо?': 'Master: Dare?',
  'Открой все достижения «Слабо?»': 'Unlock all achievements in “Dare?”',
  'Мастер «Слабо?»': 'Master of “Dare?”',
  'Соверши фирменный приём игры «Викторина»': 'Pull off the signature move in “Quiz”',
  'Впервые пройди матч в «Викторина»': 'Win your first match in “Quiz”',
  'Играй в «Викторина»': 'Play “Quiz”',
  'Побеждай в «Викторина»': 'Win in “Quiz”',
  'Обыгрывай живых соперников в «Викторина»': 'Beat live opponents in “Quiz”',
  'Сыграй во всех режимах «Викторина»': 'Play all modes of “Quiz”',
  'Мастер: Викторина': 'Master: Quiz',
  'Открой все достижения «Викторина»': 'Unlock all achievements in “Quiz”',
  'Мастер «Викторина»': 'Master of “Quiz”',
  'Соверши фирменный приём игры «Крот»': 'Pull off the signature move in “The Mole”',
  'Впервые пройди матч в «Крот»': 'Win your first match in “The Mole”',
  'Играй в «Крот»': 'Play “The Mole”',
  'Побеждай в «Крот»': 'Win in “The Mole”',
  'Обыгрывай живых соперников в «Крот»': 'Beat live opponents in “The Mole”',
  'Сыграй во всех режимах «Крот»': 'Play all modes of “The Mole”',
  'Мастер: Крот': 'Master: The Mole',
  'Открой все достижения «Крот»': 'Unlock all achievements in “The Mole”',
  'Мастер «Крот»': 'Master of “The Mole”',
  'Соверши фирменный приём игры «Домино»': 'Pull off the signature move in “Dominoes”',
  'Впервые пройди матч в «Домино»': 'Win your first match in “Dominoes”',
  'Играй в «Домино»': 'Play “Dominoes”',
  'Побеждай в «Домино»': 'Win in “Dominoes”',
  'Обыгрывай живых соперников в «Домино»': 'Beat live opponents in “Dominoes”',
  'Сыграй во всех режимах «Домино»': 'Play all modes of “Dominoes”',
  'Мастер: Домино': 'Master: Dominoes',
  'Открой все достижения «Домино»': 'Unlock all achievements in “Dominoes”',
  'Мастер «Домино»': 'Master of “Dominoes”',
  'Соверши фирменный приём игры «Лото»': 'Pull off the signature move in “Bingo”',
  'Впервые пройди матч в «Лото»': 'Win your first match in “Bingo”',
  'Играй в «Лото»': 'Play “Bingo”',
  'Побеждай в «Лото»': 'Win in “Bingo”',
  'Обыгрывай живых соперников в «Лото»': 'Beat live opponents in “Bingo”',
  'Сыграй во всех режимах «Лото»': 'Play all modes of “Bingo”',
  'Мастер: Лото': 'Master: Bingo',
  'Открой все достижения «Лото»': 'Unlock all achievements in “Bingo”',
  'Мастер «Лото»': 'Master of “Bingo”',
  'Соверши фирменный приём игры «Лесенки»': 'Pull off the signature move in “Snakes & Ladders”',
  'Впервые пройди матч в «Лесенки»': 'Win your first match in “Snakes & Ladders”',
  'Играй в «Лесенки»': 'Play “Snakes & Ladders”',
  'Побеждай в «Лесенки»': 'Win in “Snakes & Ladders”',
  'Обыгрывай живых соперников в «Лесенки»': 'Beat live opponents in “Snakes & Ladders”',
  'Сыграй во всех режимах «Лесенки»': 'Play all modes of “Snakes & Ladders”',
  'Мастер: Лесенки': 'Master: Snakes & Ladders',
  'Открой все достижения «Лесенки»': 'Unlock all achievements in “Snakes & Ladders”',
  'Мастер «Лесенки»': 'Master of “Snakes & Ladders”',
  'Соверши фирменный приём игры «Магнат»': 'Pull off the signature move in “Tycoon”',
  'Впервые пройди матч в «Магнат»': 'Win your first match in “Tycoon”',
  'Играй в «Магнат»': 'Play “Tycoon”',
  'Побеждай в «Магнат»': 'Win in “Tycoon”',
  'Обыгрывай живых соперников в «Магнат»': 'Beat live opponents in “Tycoon”',
  'Сыграй во всех режимах «Магнат»': 'Play all modes of “Tycoon”',
  'Мастер: Магнат': 'Master: Tycoon',
  'Открой все достижения «Магнат»': 'Unlock all achievements in “Tycoon”',
  'Мастер «Магнат»': 'Master of “Tycoon”',
  'Соверши фирменный приём игры «Морской бой»': 'Pull off the signature move in “Battleship”',
  'Впервые пройди матч в «Морской бой»': 'Win your first match in “Battleship”',
  'Играй в «Морской бой»': 'Play “Battleship”',
  'Побеждай в «Морской бой»': 'Win in “Battleship”',
  'Обыгрывай живых соперников в «Морской бой»': 'Beat live opponents in “Battleship”',
  'Сыграй во всех режимах «Морской бой»': 'Play all modes of “Battleship”',
  'Мастер: Морской бой': 'Master: Battleship',
  'Открой все достижения «Морской бой»': 'Unlock all achievements in “Battleship”',
  'Мастер «Морской бой»': 'Master of “Battleship”',
  'Соверши фирменный приём игры «Маджонг»': 'Pull off the signature move in “Mahjong”',
  'Впервые пройди матч в «Маджонг»': 'Win your first match in “Mahjong”',
  'Играй в «Маджонг»': 'Play “Mahjong”',
  'Побеждай в «Маджонг»': 'Win in “Mahjong”',
  'Обыгрывай живых соперников в «Маджонг»': 'Beat live opponents in “Mahjong”',
  'Сыграй во всех режимах «Маджонг»': 'Play all modes of “Mahjong”',
  'Мастер: Маджонг': 'Master: Mahjong',
  'Открой все достижения «Маджонг»': 'Unlock all achievements in “Mahjong”',
  'Мастер «Маджонг»': 'Master of “Mahjong”',
  'Соверши фирменный приём игры «Реверси»': 'Pull off the signature move in “Reversi”',
  'Впервые пройди матч в «Реверси»': 'Win your first match in “Reversi”',
  'Играй в «Реверси»': 'Play “Reversi”',
  'Побеждай в «Реверси»': 'Win in “Reversi”',
  'Обыгрывай живых соперников в «Реверси»': 'Beat live opponents in “Reversi”',
  'Сыграй во всех режимах «Реверси»': 'Play all modes of “Reversi”',
  'Мастер: Реверси': 'Master: Reversi',
  'Открой все достижения «Реверси»': 'Unlock all achievements in “Reversi”',
  'Мастер «Реверси»': 'Master of “Reversi”',
  'Соверши фирменный приём игры «Паук»': 'Pull off the signature move in “Spider”',
  'Впервые пройди матч в «Паук»': 'Win your first match in “Spider”',
  'Играй в «Паук»': 'Play “Spider”',
  'Побеждай в «Паук»': 'Win in “Spider”',
  'Обыгрывай живых соперников в «Паук»': 'Beat live opponents in “Spider”',
  'Сыграй во всех режимах «Паук»': 'Play all modes of “Spider”',
  'Мастер: Паук': 'Master: Spider',
  'Открой все достижения «Паук»': 'Unlock all achievements in “Spider”',
  'Мастер «Паук»': 'Master of “Spider”',
  'Соверши фирменный приём игры «Виселица»': 'Pull off the signature move in “Hangman”',
  'Впервые пройди матч в «Виселица»': 'Win your first match in “Hangman”',
  'Играй в «Виселица»': 'Play “Hangman”',
  'Побеждай в «Виселица»': 'Win in “Hangman”',
  'Обыгрывай живых соперников в «Виселица»': 'Beat live opponents in “Hangman”',
  'Сыграй во всех режимах «Виселица»': 'Play all modes of “Hangman”',
  'Мастер: Виселица': 'Master: Hangman',
  'Открой все достижения «Виселица»': 'Unlock all achievements in “Hangman”',
  'Мастер «Виселица»': 'Master of “Hangman”',
  'Соверши фирменный приём игры «Буквица»': 'Pull off the signature move in “Word Board”',
  'Впервые пройди матч в «Буквица»': 'Win your first match in “Word Board”',
  'Играй в «Буквица»': 'Play “Word Board”',
  'Побеждай в «Буквица»': 'Win in “Word Board”',
  'Обыгрывай живых соперников в «Буквица»': 'Beat live opponents in “Word Board”',
  'Сыграй во всех режимах «Буквица»': 'Play all modes of “Word Board”',
  'Мастер: Буквица': 'Master: Word Board',
  'Открой все достижения «Буквица»': 'Unlock all achievements in “Word Board”',
  'Мастер «Буквица»': 'Master of “Word Board”',
  'Соверши фирменный приём игры «Плетёнка»': 'Pull off the signature move in “Word Weave”',
  'Впервые пройди матч в «Плетёнка»': 'Win your first match in “Word Weave”',
  'Играй в «Плетёнка»': 'Play “Word Weave”',
  'Побеждай в «Плетёнка»': 'Win in “Word Weave”',
  'Обыгрывай живых соперников в «Плетёнка»': 'Beat live opponents in “Word Weave”',
  'Сыграй во всех режимах «Плетёнка»': 'Play all modes of “Word Weave”',
  'Мастер: Плетёнка': 'Master: Word Weave',
  'Открой все достижения «Плетёнка»': 'Unlock all achievements in “Word Weave”',
  'Мастер «Плетёнка»': 'Master of “Word Weave”',
  'Соверши фирменный приём игры «Хрумик»': 'Pull off the signature move in “Muncher”',
  'Впервые пройди матч в «Хрумик»': 'Win your first match in “Muncher”',
  'Играй в «Хрумик»': 'Play “Muncher”',
  'Побеждай в «Хрумик»': 'Win in “Muncher”',
  'Обыгрывай живых соперников в «Хрумик»': 'Beat live opponents in “Muncher”',
  'Сыграй во всех режимах «Хрумик»': 'Play all modes of “Muncher”',
  'Мастер: Хрумик': 'Master: Muncher',
  'Открой все достижения «Хрумик»': 'Unlock all achievements in “Muncher”',
  'Мастер «Хрумик»': 'Master of “Muncher”',
  'Соверши фирменный приём игры «Пузырик»': 'Pull off the signature move in “Bubbles”',
  'Впервые пройди матч в «Пузырик»': 'Win your first match in “Bubbles”',
  'Играй в «Пузырик»': 'Play “Bubbles”',
  'Побеждай в «Пузырик»': 'Win in “Bubbles”',
  'Обыгрывай живых соперников в «Пузырик»': 'Beat live opponents in “Bubbles”',
  'Сыграй во всех режимах «Пузырик»': 'Play all modes of “Bubbles”',
  'Мастер: Пузырик': 'Master: Bubbles',
  'Открой все достижения «Пузырик»': 'Unlock all achievements in “Bubbles”',
  'Мастер «Пузырик»': 'Master of “Bubbles”',
  'Соверши фирменный приём игры «Шайбус»': 'Pull off the signature move in “Air Hockey”',
  'Впервые пройди матч в «Шайбус»': 'Win your first match in “Air Hockey”',
  'Играй в «Шайбус»': 'Play “Air Hockey”',
  'Побеждай в «Шайбус»': 'Win in “Air Hockey”',
  'Обыгрывай живых соперников в «Шайбус»': 'Beat live opponents in “Air Hockey”',
  'Сыграй во всех режимах «Шайбус»': 'Play all modes of “Air Hockey”',
  'Мастер: Шайбус': 'Master: Air Hockey',
  'Открой все достижения «Шайбус»': 'Unlock all achievements in “Air Hockey”',
  'Мастер «Шайбус»': 'Master of “Air Hockey”',
  'Соверши фирменный приём игры «Дуплет»': 'Pull off the signature move in “8-Ball”',
  'Впервые пройди матч в «Дуплет»': 'Win your first match in “8-Ball”',
  'Играй в «Дуплет»': 'Play “8-Ball”',
  'Побеждай в «Дуплет»': 'Win in “8-Ball”',
  'Обыгрывай живых соперников в «Дуплет»': 'Beat live opponents in “8-Ball”',
  'Сыграй во всех режимах «Дуплет»': 'Play all modes of “8-Ball”',
  'Мастер: Дуплет': 'Master: 8-Ball',
  'Открой все достижения «Дуплет»': 'Unlock all achievements in “8-Ball”',
  'Мастер «Дуплет»': 'Master of “8-Ball”',
  'Соверши фирменный приём игры «Рикошет»': 'Pull off the signature move in “Ricochet”',
  'Впервые пройди матч в «Рикошет»': 'Win your first match in “Ricochet”',
  'Играй в «Рикошет»': 'Play “Ricochet”',
  'Побеждай в «Рикошет»': 'Win in “Ricochet”',
  'Обыгрывай живых соперников в «Рикошет»': 'Beat live opponents in “Ricochet”',
  'Сыграй во всех режимах «Рикошет»': 'Play all modes of “Ricochet”',
  'Мастер: Рикошет': 'Master: Ricochet',
  'Открой все достижения «Рикошет»': 'Unlock all achievements in “Ricochet”',
  'Мастер «Рикошет»': 'Master of “Ricochet”',
  'Соверши фирменный приём игры «Танчики»': 'Pull off the signature move in “Tanks”',
  'Впервые пройди матч в «Танчики»': 'Win your first match in “Tanks”',
  'Играй в «Танчики»': 'Play “Tanks”',
  'Побеждай в «Танчики»': 'Win in “Tanks”',
  'Обыгрывай живых соперников в «Танчики»': 'Beat live opponents in “Tanks”',
  'Сыграй во всех режимах «Танчики»': 'Play all modes of “Tanks”',
  'Мастер: Танчики': 'Master: Tanks',
  'Открой все достижения «Танчики»': 'Unlock all achievements in “Tanks”',
  'Мастер «Танчики»': 'Master of “Tanks”',
  'Соверши фирменный приём игры «Забава»': 'Pull off the signature move in “Fun Pack”',
  'Впервые пройди матч в «Забава»': 'Win your first match in “Fun Pack”',
  'Играй в «Забава»': 'Play “Fun Pack”',
  'Побеждай в «Забава»': 'Win in “Fun Pack”',
  'Обыгрывай живых соперников в «Забава»': 'Beat live opponents in “Fun Pack”',
  'Сыграй во всех режимах «Забава»': 'Play all modes of “Fun Pack”',
  'Мастер: Забава': 'Master: Fun Pack',
  'Открой все достижения «Забава»': 'Unlock all achievements in “Fun Pack”',
  'Мастер «Забава»': 'Master of “Fun Pack”',
  'Соверши фирменный приём игры «Клеточки»': 'Pull off the signature move in “Nonograms”',
  'Впервые пройди матч в «Клеточки»': 'Win your first match in “Nonograms”',
  'Играй в «Клеточки»': 'Play “Nonograms”',
  'Побеждай в «Клеточки»': 'Win in “Nonograms”',
  'Обыгрывай живых соперников в «Клеточки»': 'Beat live opponents in “Nonograms”',
  'Сыграй во всех режимах «Клеточки»': 'Play all modes of “Nonograms”',
  'Мастер: Клеточки': 'Master: Nonograms',
  'Открой все достижения «Клеточки»': 'Unlock all achievements in “Nonograms”',
  'Мастер «Клеточки»': 'Master of “Nonograms”',
  'Соверши фирменный приём игры «Кубик»': 'Pull off the signature move in “Cube”',
  'Впервые пройди матч в «Кубик»': 'Win your first match in “Cube”',
  'Играй в «Кубик»': 'Play “Cube”',
  'Побеждай в «Кубик»': 'Win in “Cube”',
  'Обыгрывай живых соперников в «Кубик»': 'Beat live opponents in “Cube”',
  'Сыграй во всех режимах «Кубик»': 'Play all modes of “Cube”',
  'Мастер: Кубик': 'Master: Cube',
  'Открой все достижения «Кубик»': 'Unlock all achievements in “Cube”',
  'Мастер «Кубик»': 'Master of “Cube”',
  'Соверши фирменный приём игры «Линик»': 'Pull off the signature move in “Lines”',
  'Впервые пройди матч в «Линик»': 'Win your first match in “Lines”',
  'Играй в «Линик»': 'Play “Lines”',
  'Побеждай в «Линик»': 'Win in “Lines”',
  'Обыгрывай живых соперников в «Линик»': 'Beat live opponents in “Lines”',
  'Сыграй во всех режимах «Линик»': 'Play all modes of “Lines”',
  'Мастер: Линик': 'Master: Lines',
  'Открой все достижения «Линик»': 'Unlock all achievements in “Lines”',
  'Мастер «Линик»': 'Master of “Lines”',
  'Соверши фирменный приём игры «Складик»': 'Pull off the signature move in “Sokoban”',
  'Впервые пройди матч в «Складик»': 'Win your first match in “Sokoban”',
  'Играй в «Складик»': 'Play “Sokoban”',
  'Побеждай в «Складик»': 'Win in “Sokoban”',
  'Обыгрывай живых соперников в «Складик»': 'Beat live opponents in “Sokoban”',
  'Сыграй во всех режимах «Складик»': 'Play all modes of “Sokoban”',
  'Мастер: Складик': 'Master: Sokoban',
  'Открой все достижения «Складик»': 'Unlock all achievements in “Sokoban”',
  'Мастер «Складик»': 'Master of “Sokoban”',
  'Соверши фирменный приём игры «Четыре в ряд»': 'Pull off the signature move in “Four in a Row”',
  'Впервые пройди матч в «Четыре в ряд»': 'Win your first match in “Four in a Row”',
  'Играй в «Четыре в ряд»': 'Play “Four in a Row”',
  'Побеждай в «Четыре в ряд»': 'Win in “Four in a Row”',
  'Обыгрывай живых соперников в «Четыре в ряд»': 'Beat live opponents in “Four in a Row”',
  'Сыграй во всех режимах «Четыре в ряд»': 'Play all modes of “Four in a Row”',
  'Мастер: Четыре в ряд': 'Master: Four in a Row',
  'Открой все достижения «Четыре в ряд»': 'Unlock all achievements in “Four in a Row”',
  'Мастер «Четыре в ряд»': 'Master of “Four in a Row”',
  'Соверши фирменный приём игры «Го»': 'Pull off the signature move in “Go”',
  'Впервые пройди матч в «Го»': 'Win your first match in “Go”',
  'Играй в «Го»': 'Play “Go”',
  'Побеждай в «Го»': 'Win in “Go”',
  'Обыгрывай живых соперников в «Го»': 'Beat live opponents in “Go”',
  'Сыграй во всех режимах «Го»': 'Play all modes of “Go”',
  'Мастер: Го': 'Master: Go',
  'Открой все достижения «Го»': 'Unlock all achievements in “Go”',
  'Мастер «Го»': 'Master of “Go”',
  'Соверши фирменный приём игры «Сёги»': 'Pull off the signature move in “Shogi”',
  'Впервые пройди матч в «Сёги»': 'Win your first match in “Shogi”',
  'Играй в «Сёги»': 'Play “Shogi”',
  'Побеждай в «Сёги»': 'Win in “Shogi”',
  'Обыгрывай живых соперников в «Сёги»': 'Beat live opponents in “Shogi”',
  'Сыграй во всех режимах «Сёги»': 'Play all modes of “Shogi”',
  'Мастер: Сёги': 'Master: Shogi',
  'Открой все достижения «Сёги»': 'Unlock all achievements in “Shogi”',
  'Мастер «Сёги»': 'Master of “Shogi”',
  'Соверши фирменный приём игры «Сянци»': 'Pull off the signature move in “Xiangqi”',
  'Впервые пройди матч в «Сянци»': 'Win your first match in “Xiangqi”',
  'Играй в «Сянци»': 'Play “Xiangqi”',
  'Побеждай в «Сянци»': 'Win in “Xiangqi”',
  'Обыгрывай живых соперников в «Сянци»': 'Beat live opponents in “Xiangqi”',
  'Сыграй во всех режимах «Сянци»': 'Play all modes of “Xiangqi”',
  'Мастер: Сянци': 'Master: Xiangqi',
  'Открой все достижения «Сянци»': 'Unlock all achievements in “Xiangqi”',
  'Мастер «Сянци»': 'Master of “Xiangqi”',
  'Соверши фирменный приём игры «Легион»': 'Pull off the signature move in “Legion”',
  'Впервые пройди матч в «Легион»': 'Win your first match in “Legion”',
  'Играй в «Легион»': 'Play “Legion”',
  'Побеждай в «Легион»': 'Win in “Legion”',
  'Обыгрывай живых соперников в «Легион»': 'Beat live opponents in “Legion”',
  'Сыграй во всех режимах «Легион»': 'Play all modes of “Legion”',
  'Мастер: Легион': 'Master: Legion',
  'Открой все достижения «Легион»': 'Unlock all achievements in “Legion”',
  'Мастер «Легион»': 'Master of “Legion”',
  'Соверши фирменный приём игры «Натиск»': 'Pull off the signature move in “Onslaught”',
  'Впервые пройди матч в «Натиск»': 'Win your first match in “Onslaught”',
  'Играй в «Натиск»': 'Play “Onslaught”',
  'Побеждай в «Натиск»': 'Win in “Onslaught”',
  'Обыгрывай живых соперников в «Натиск»': 'Beat live opponents in “Onslaught”',
  'Сыграй во всех режимах «Натиск»': 'Play all modes of “Onslaught”',
  'Мастер: Натиск': 'Master: Onslaught',
  'Открой все достижения «Натиск»': 'Unlock all achievements in “Onslaught”',
  'Мастер «Натиск»': 'Master of “Onslaught”',
  'Побеждай в играх жанра «Карты»': 'Win games in the “Cards” genre',
  'Карты: 10': 'Cards: 10',
  'Карты: 50': 'Cards: 50',
  'Карты: 200': 'Cards: 200',
  'Побеждай в играх жанра «Настольные»': 'Win games in the “Board” genre',
  'Настольные: 10': 'Board: 10',
  'Настольные: 50': 'Board: 50',
  'Настольные: 200': 'Board: 200',
  'Побеждай в играх жанра «Компания»': 'Win games in the “Party” genre',
  'Компания: 10': 'Party: 10',
  'Компания: 50': 'Party: 50',
  'Компания: 200': 'Party: 200',
  'Побеждай в играх жанра «Слова»': 'Win games in the “Words” genre',
  'Слова: 10': 'Words: 10',
  'Слова: 50': 'Words: 50',
  'Слова: 200': 'Words: 200',
  'Побеждай в играх жанра «Аркады»': 'Win games in the “Arcade” genre',
  'Аркады: 10': 'Arcade: 10',
  'Аркады: 50': 'Arcade: 50',
  'Аркады: 200': 'Arcade: 200',
  'Побеждай в играх жанра «Головоломки»': 'Win games in the “Puzzle” genre',
  'Головоломки: 10': 'Puzzle: 10',
  'Головоломки: 50': 'Puzzle: 50',
  'Головоломки: 200': 'Puzzle: 200',
  'Побеждай в играх жанра «Стратегии»': 'Win games in the “Strategy” genre',
  'Стратегии: 10': 'Strategy: 10',
  'Стратегии: 50': 'Strategy: 50',
  'Стратегии: 200': 'Strategy: 200',

  // -- Наборы Game (auto-added) --
  'Горсть Game': 'Handful of Game',
  'Мешочек Game': 'Pouch of Game',
  'Сундук Game': 'Chest of Game',
  'Клад Game': 'Treasure of Game',
}
