// Английский словарь для хаба. Ключ — русская исходная строка (см. i18n.ts).
// Если строки нет в словаре, t() вернёт русский ключ (безопасный фолбэк).
export const EN: Record<string, string> = {
  // ── Навигация / вкладки ──────────────────────────────────────────────
  'Дом': 'Home',
  'Магазин': 'Shop',
  'Аватар': 'Avatar',
  'Друзья': 'Friends',
  'Профиль': 'Profile',
  'Звук': 'Sound',
  'Помощь': 'Help',
  'Магазин стиля': 'Style shop',
  'Хаб': 'Hub',

  // ── Загрузка / общие ─────────────────────────────────────────────────
  'Открываем игровую…': 'Opening the arcade…',
  'Загрузка магазина…': 'Loading the shop…',
  'Загрузка профиля…': 'Loading profile…',
  'Загрузка стиля…': 'Loading style…',
  'Загрузка коллекций…': 'Loading collections…',
  'Загрузка барахолки…': 'Loading the market…',
  'Загрузка рейтингов…': 'Loading leaderboards…',
  'Загрузка сезона…': 'Loading the season…',
  'Открываем витрину…': 'Opening the showcase…',
  'Открываем гардероб…': 'Opening the wardrobe…',
  'Событие завершилось.': 'The event has ended.',
  'Понятно': 'Got it',
  'Закрыть': 'Close',
  'Выйти': 'Leave',
  'Предмет': 'Item',
  'нет': 'none',
  'Игрок': 'Player',
  'забрать': 'claim',
  'Куплено': 'Owned',

  // ── App: листы About/Help/Settings ──────────────────────────────────
  'Game is Game': 'Game is Game',
  'Все наши игры в одном месте': 'All our games in one place',
  'Один аккаунт, все наши игры. Открываешь хаб, выбираешь игру, и она запускается сразу. Друзья, уровни и значки общие для всех игр.':
    'One account, all our games. Open the hub, pick a game, and it launches instantly. Friends, levels and badges are shared across every game.',
  'Как это работает': 'How it works',
  'Выбери игру в «Доме», она откроется сразу. Добавляй друзей по коду, соревнуйся в «Ленте» и качай уровень за запуски игр.':
    'Pick a game on the Home tab and it opens right away. Add friends by code, compete in the Feed, and level up by playing games.',
  'открыть хаб': 'open the hub',
  'список игр': 'list of games',
  'помощь': 'help',
  'Настройки': 'Settings',
  'Тихие щелчки в интерфейсе': 'Quiet clicks in the interface',
  'Об этом приложении': 'About this app',
  'Что такое Game is Game': 'What Game is Game is',
  'Как пользоваться хабом': 'How to use the hub',
  'Сделано с любовью ♥': 'Made with love ♥',
  'Язык': 'Language',
  'Русский или English': 'Russian or English',

  // ── Профиль-редактор ─────────────────────────────────────────────────
  'Ник': 'Username',
  'Ник берётся из твоего Telegram и общий для всех наших игр.':
    'Your username comes from Telegram and is shared across all our games.',
  'Придумай ник': 'Pick a username',
  'ник': 'username',
  'В Telegram у тебя нет @username, поэтому выбери свой, 3-32 символа: латиница, цифры и «_». Его больше никто не сможет занять.':
    "You don't have a Telegram @username, so pick your own: 3–32 characters, Latin letters, digits and “_”. No one else will be able to take it.",
  'Закрепить ник': 'Lock in username',
  'Сменить образ': 'Change look',
  'Ник: 3-32 символа, латиница, цифры и _': 'Username: 3–32 characters, Latin letters, digits and _',
  'Этот ник уже занят, придумай другой': 'That username is taken, pick another',
  'Ник уже закреплён': 'Username already locked',
  'Недопустимый ник': 'Invalid username',

  // ── Коллекции ────────────────────────────────────────────────────────
  'Коллекции': 'Collections',
  'Собери все предметы коллекции и получи бонус Game.': 'Collect every item in a collection to earn a Game bonus.',

  // ── Команды / кланы ──────────────────────────────────────────────────
  'участников': 'members',
  'лидер': 'leader',
  'участник': 'member',
  'Общая цель недели': 'Weekly team goal',
  'Состав': 'Roster',
  'Топ команд': 'Top teams',
  'Команды': 'Teams',
  'Собери команду, бейте общие цели и поднимайтесь в топе.':
    'Build a team, hit shared goals and climb the rankings together.',
  'Создать команду': 'Create a team',
  'Название': 'Name',
  'ТЕГ': 'TAG',
  'Создать': 'Create',
  'Найти команду': 'Find a team',
  'Пока команд нет, создай первую!': 'No teams yet — create the first one!',
  'Вступить': 'Join',

  // ── Барахолка / рынок ────────────────────────────────────────────────
  'Барахолка': 'Market',
  'Выставить свой образ': 'List your item',
  'Нет торгуемых образов. Купи что-нибудь в магазине.': 'No tradeable items. Buy something in the shop first.',
  'Выбери образ…': 'Pick an item…',
  'Цена': 'Price',
  'Продать': 'Sell',
  'Мои лоты': 'My listings',
  'Снять': 'Cancel',
  'Лоты игроков': 'Player listings',
  'Пока пусто': "It's empty here",
  'Загляни позже, тут появятся образы игроков.': 'Check back later — player items will show up here.',
  'Купить': 'Buy',

  // ── Рейтинги ─────────────────────────────────────────────────────────
  'Рейтинги': 'Leaderboards',
  'GG-лига': 'GG League',
  'Неделя': 'Week',
  'Играй и зарабатывай, рейтинг наполнится.': 'Play and earn — the leaderboard will fill up.',
  'Бронза': 'Bronze',
  'Серебро': 'Silver',
  'Золото': 'Gold',
  'Платина': 'Platinum',
  'Алмаз': 'Diamond',
  'Мастер': 'Master',
  'Грандмастер': 'Grandmaster',

  // ── Событие / фестиваль ──────────────────────────────────────────────
  'Общая цель': 'Community goal',
  'Задания события': 'Event quests',
  'Магазин события': 'Event shop',

  // ── Сезонный пропуск ─────────────────────────────────────────────────
  'Бесплатно': 'Free',
  'Премиум': 'Premium',
  'максимум': 'maxed',
  'дальше:': 'next:',
  'Пропуск пройден 🏆': 'Pass completed 🏆',
  'Премиум активен ✨': 'Premium active ✨',
  'все награды премиум-трека': 'all premium-track rewards',
  'Пропуск+ 🔥': 'Pass+ 🔥',
  'мгновенно продвинуться по пропуску': 'jump ahead on the pass instantly',
  'получено': 'claimed',
  'Моя GG-лига:': 'My GG League:',

  // ── Home ─────────────────────────────────────────────────────────────
  'Найти игру…': 'Find a game…',
  'Поиск по играм': 'Search games',
  'Очистить': 'Clear',
  'Все': 'All',
  'Избранное': 'Favorites',
  'Друзья в сети 🟢': 'Friends online 🟢',
  'в сети': 'online',
  'Продолжить': 'Continue',
  'Популярное': 'Popular',
  'Снова в деле': 'Back in action',
  'Начни здесь': 'Start here',
  'Играть': 'Play',
  'Найдено': 'Found',
  'Все игры': 'All games',
  'В избранном пусто': 'No favorites yet',
  'Ничего не нашлось': 'Nothing found',
  'Отмечай игры звёздочкой, и они соберутся здесь.': 'Star games and they will gather here.',
  'Попробуй другое название или сними фильтры.': 'Try another name or clear the filters.',
  'Недавнее': 'Recent',
  'Убрать из избранного': 'Remove from favorites',
  'В избранное': 'Add to favorite',
  'Задания дня': 'Daily quests',
  'новые каждый день': 'new every day',
  'Задания недели': 'Weekly quests',
  'сброс в понедельник': 'resets Monday',
  'Игра недели': 'Game of the week',
  'Открыть →': 'Open →',
  'осталось': 'left',
  'Пропуск': 'Pass',
  'тир': 'tier',
  'Тир': 'Tier',
  'Уровень': 'Level',
  'Ур.': 'Lvl',

  // ── Карточка игры ────────────────────────────────────────────────────
  'Одиночная': 'Solo',
  'С друзьями': 'With friends',
  'Один и с друзьями': 'Solo & with friends',
  'запуск': 'launch',
  'запусков': 'launches',
  'в игре': 'in game',
  'Оцени первым': 'Be the first to rate',
  'Нравится': 'Like',
  'Не очень': 'Not great',
  'В избранном': 'Favorited',
  'Слежу': 'Following',
  'Следить': 'Follow',
  'Поделиться с друзьями': 'Share with friends',
  'Секрет': 'Secret',
  'Скрытое достижение: открой, чтобы узнать': 'Hidden achievement: unlock to reveal',
  'Максимум взят': 'Maxed out',
  'редкое': 'rare',

  // ── Задания / квесты ─────────────────────────────────────────────────
  'Заменить задание': 'Reroll quest',
  'замена: 1 бесплатно': 'reroll: 1 free',

  // ── Профиль ──────────────────────────────────────────────────────────
  'Серия': 'Streak',
  'Друзей': 'Friends',
  'рек.': 'best',
  'дней': 'days',
  'порвалась, восстанови за 24 ч!': 'broke — restore it within 24h!',
  '▶ 3 игры даром': '▶ 3 games free',
  'Игры': 'Games',
  'Престиж: сбросить уровень за звезду': 'Prestige: reset your level for a star',
  'Статистика игр': 'Game stats',
  'Значки': 'Badges',
  'Достижения': 'Achievements',
  'По играм': 'By game',
  'игр': 'games',
  'КОД ДРУГА': 'FRIEND CODE',
  'Код скопирован ✨': 'Code copied ✨',
  'Редактировать имя': 'Edit name',

  // ── Друзья ───────────────────────────────────────────────────────────
  'Лидеры': 'Leaders',
  'Лента': 'Feed',
  'Зови друзей, получай Game': 'Invite friends, earn Game',
  'Пригласить друга': 'Invite a friend',
  'Дружеские серии 🔥🤝': 'Friend streaks 🔥🤝',
  'играйте в один день': 'play on the same day',
  'Кооп-квесты 🤝': 'Co-op quests 🤝',
  'вместе с другом': 'together with a friend',
  'Твой код друга': 'Your friend code',
  'Копировать': 'Copy',
  'Поделиться': 'Share',
  'Добавить друга': 'Add a friend',
  'Код, напр. K7M2QX': 'Code, e.g. K7M2QX',
  'Добавить': 'Add',
  'Команда': 'Team',
  'Мои друзья': 'My friends',
  'Пока никого': 'No one yet',
  'Поделись кодом или добавь друга, и играйте вместе.': 'Share your code or add a friend, and play together.',
  'Глобальные рейтинги': 'Global leaderboards',
  'Таблица пустеет': 'The board is empty',
  'Добавь друзей и запускай игры. Появится рейтинг по опыту.':
    'Add friends and play games. A leaderboard by XP will appear.',
  'Тихо пока': 'Quiet for now',
  'Когда ты или друзья запускаете игры, события появятся здесь.':
    'When you or your friends play games, events will show up here.',
  'Подарить Game': 'Gift Game',
  'до 3 в день': 'up to 3 a day',
  'Или подари предмет': 'Or gift an item',
  'Дарить можно только покупные вещи, заслуги остаются с тобой.':
    'You can only gift purchased items — earned rewards stay with you.',
  'Не хватает Game': 'Not enough Game',
  'Лимит: 5 подарков в день': 'Limit: 5 gifts a day',
  'Вы не в друзьях': "You're not friends",
  'От 10 до 1000 Game': 'From 10 to 1000 Game',
  'Код не найден': 'Code not found',
  'Это твой код 🙂': "That's your own code 🙂",
  'Уже в друзьях': 'Already friends',
  'Не получилось': "That didn't work",
  'У друга уже есть этот предмет': 'Your friend already has this item',
  'Лимит подарков-предметов на сегодня': "Item-gift limit reached for today",
  'Не получилось подарить предмет': "Couldn't gift the item",
  'Не получилось отправить': "Couldn't send",
  'добавлен 🎉': 'added 🎉',
  'Приглашено:': 'Invited:',
  'Заработано:': 'Earned:',
  'пни 👉': 'nudge 👉',
  '✓ награда забрана': '✓ reward claimed',
  'играет в': 'playing',
  'был(а)': 'seen',
  'давно не заходил(а)': "hasn't been around",
  'Бросить вызов:': 'Challenge:',
  'Кооп-квест:': 'Co-op quest:',
  'Подарить Game:': 'Gift Game:',
  'Удалить из друзей': 'Remove friend',
  'ты': 'you',
  'открыл(а)': 'opened',
  'игру': 'a game',
  'Подарок отправлен:': 'Gift sent:',
  'обрадуется 🎁': 'will be delighted 🎁',

  // ── Магазин ──────────────────────────────────────────────────────────
  'Магазин стиля ': 'Style shop',
  'Зарабатывай Game в играх и собирай редкие образы': 'Earn Game in games and collect rare looks',
  'Витрина дня': 'Daily showcase',
  'новое каждый день': 'new every day',
  'уходит скоро': 'leaving soon',
  'Коллекции ': 'Collections',
  'Косметика': 'Cosmetics',
  'Всё': 'All',
  'Здесь пусто': "It's empty here",
  'В этой категории пока нет товаров.': 'No items in this category yet.',
  'Пополнить баланс': 'Top up balance',
  'за Telegram Stars': 'with Telegram Stars',
  '×2 первая': '×2 first buy',
  'Скоро': 'Soon',
  'Уже куплено, надень во вкладке «Аватар»': 'Already owned — equip it on the Avatar tab',
  'Скоро в продаже ✨': 'Coming soon ✨',
  'Не хватает Game 💰': 'Not enough Game 💰',

  // ── Стиль / аватар ───────────────────────────────────────────────────
  'Не хватает Game 💰, загляни в Магазин': 'Not enough Game 💰 — check the Shop',
  'Этот предмет закрыт 🔒': 'This item is locked 🔒',
  'Перекрасить тело': 'Recolor body',
  'сброс бесплатно': 'reset is free',
  'оригинал': 'original',
  'оттенок': 'hue',
  'Откроется:': 'Unlocks at:',

  // ── Слоты косметики ──────────────────────────────────────────────────
  'Цвет': 'Color',
  'Лицо': 'Face',
  'Рамка': 'Frame',
  'Шляпа': 'Hat',
  'Очки': 'Eyewear',
  'Эффект': 'Effect',
  'Питомец': 'Pet',
  'Баннер': 'Banner',
  'Титул': 'Title',

  // ── Редкости ─────────────────────────────────────────────────────────
  'Обычная': 'Common',
  'Редкая': 'Rare',
  'Эпическая': 'Epic',
  'Легендарная': 'Legendary',
  'Мифическая': 'Mythic',

  // ── Категории игр ────────────────────────────────────────────────────
  'Карты': 'Cards',
  'Настольные': 'Board',
  'Компания': 'Party',
  'Слова': 'Words',
  'Аркады': 'Arcade',
  'Головоломки': 'Puzzle',
  'Стратегии': 'Strategy',

  // ── Тосты store.ts ───────────────────────────────────────────────────
  'Друг': 'Friend',
  'пригласил(а) тебя! Сыграй 5 игр и получишь': 'invited you! Play 5 games and get',
  'Вызов принят:': 'Challenge accepted:',
  'теперь в друзьях 🎉': 'is now your friend 🎉',
  'Задание выполнено:': 'Quest complete:',
  'Уровень сброшен, вперёд по новой!': 'Level reset — off you go again!',
  'Серия восстановлена 🔧🔥': 'Streak restored 🔧🔥',
  'Награда получена:': 'Reward claimed:',
  'Коллекция собрана:': 'Collection complete:',
  'создана 🛡️': 'created 🛡️',
  'Ты в команде': "You're in the team",
  'Награда события:': 'Event reward:',
  'куплено 🎉': 'purchased 🎉',
  'закреплён ✨': 'locked in ✨',
  'Награда уже получена': 'Reward already claimed',
  'Задание ещё не выполнено': 'Quest not finished yet',
  'Задание заменено': 'Quest rerolled',
  'Не удалось заменить': "Couldn't reroll",
  'Не хватает Game на реролл': 'Not enough Game to reroll',
  'Оплата прошла: Game уже на балансе 🎉': 'Payment complete: Game added to your balance 🎉',
  'Пополнение работает внутри Telegram': 'Top-up works inside Telegram',
  'Не получилось открыть счёт': "Couldn't open the invoice",
  'Друг получил напоминание 🔥🤝': 'Your friend got a nudge 🔥🤝',
  'Уже напоминал(а) сегодня': 'Already nudged today',
  'Кооп-квест начат 🤝 Играйте вместе!': 'Co-op quest started 🤝 Play together!',
  'Сначала добавь в друзья': 'Add them as a friend first',
  'Не удалось начать': "Couldn't start",
  'Кооп-награда получена 🤝': 'Co-op reward claimed 🤝',
  'Цель ещё не достигнута': 'Goal not reached yet',
  'Не удалось': "That didn't work",
  'Не удалось обновить избранное': "Couldn't update favorites",
  'Подпишем на новости этой игры 🔔': "You'll get news about this game 🔔",
  'Не удалось обновить подписку': "Couldn't update your follow",
  'Не удалось сохранить оценку': "Couldn't save your rating",
  'Престиж откроется на 100 уровне': 'Prestige unlocks at level 100',
  'Не хватает Game на ремонт': 'Not enough Game for a repair',
  'Сыграй 3 матча для бесплатного ремонта': 'Play 3 matches for a free repair',
  'Окно ремонта закрыто': 'The repair window has closed',
  'заморозка': 'freeze',
  'предмет': 'item',
  'Нужен премиум-пропуск': 'Premium pass required',
  'Тир ещё не открыт': 'Tier not unlocked yet',
  'Премиум-пропуск активирован ✨': 'Premium pass activated ✨',
  'Покупка пропуска работает внутри Telegram': 'Buying the pass works inside Telegram',
  'Лот выставлен 🏷️': 'Listing posted 🏷️',
  'Сыграй больше игр, чтобы торговать': 'Play more games to trade',
  'Цена вне допустимых границ': 'Price is out of range',
  'Лимит лотов на сегодня': "Listing limit reached for today",
  'Не удалось выставить': "Couldn't post the listing",
  'Куплено на барахолке 🎉': 'Bought on the market 🎉',
  'Лот уже продан': 'Listing already sold',
  'Не удалось купить': "Couldn't buy",
  'Лот снят': 'Listing removed',
  'Не удалось снять лот': "Couldn't remove the listing",
  'Уже получено': 'Already claimed',
  'Коллекция ещё не собрана': 'Collection not complete yet',
  'Такой тег занят': 'That tag is taken',
  'Ты уже в команде': "You're already in a team",
  'Проверь название и тег': 'Check the name and tag',
  'В команде нет мест': 'The team is full',
  'Не удалось вступить': "Couldn't join",
  'Ты покинул(а) команду': 'You left the team',
  'Награда команды получена 🎉': 'Team reward claimed 🎉',
  'Награда сообщества получена 🎉': 'Community reward claimed 🎉',
  'Куплено за 🎟': 'Bought with 🎟',
  'Не хватает 🎟': 'Not enough 🎟',
  'Этот предмет ещё закрыт': 'This item is still locked',
  'Не удалось надеть': "Couldn't equip",
  'Не хватает Game на перекраску': 'Not enough Game to recolor',
  'Не удалось перекрасить': "Couldn't recolor",
  'Покупка не удалась': 'Purchase failed',

  // ── Динамические фрагменты Home ──────────────────────────────────────
  'Открыть': 'Open',
  'играет · зайти': 'playing · join',
  'в': 'in',
  'зайти': 'join',
  'можно забрать:': 'claimable:',
  'дн.': 'd.',
  'забрать:': 'claim:',
  'Престиж': 'Prestige',
  'Идеальная серия': 'Perfect streak',

  // ── Каталог игр: названия ────────────────────────────────────────────
  'Маньяк': 'Maniac',
  'Нитро-лига': 'Nitro League',
  'Неон-Тайд': 'Neon Tide',
  'Чехарда': 'Leapfrog',
  'Однушечка': 'Wildcard',
  'Крокоша': 'Charades',
  'Секрет ночи': 'Night Secret',
  'Сакс-будильник': 'Sax Alarm',
  'Шарик': 'Buddy',
  'Картишки': 'Bad Cards',
  'Слабо?': 'Dare?',
  'Викторина': 'Quiz',
  'Крот': 'The Mole',
  'Домино': 'Dominoes',
  'Лото': 'Bingo',
  'Лесенки': 'Snakes & Ladders',
  'Магнат': 'Tycoon',
  'Морской бой': 'Battleship',
  'Маджонг': 'Mahjong',
  'Реверси': 'Reversi',
  'Паук': 'Spider',
  'Виселица': 'Hangman',
  'Буквица': 'Word Board',
  'Плетёнка': 'Word Weave',
  'Хрумик': 'Muncher',
  'Пузырик': 'Bubbles',
  'Шайбус': 'Air Hockey',
  'Дуплет': '8-Ball',
  'Рикошет': 'Ricochet',
  'Танчики': 'Tanks',
  'Забава': 'Fun Pack',
  'Клеточки': 'Nonograms',
  'Кубик': 'Cube',
  'Линик': 'Lines',
  'Складик': 'Sokoban',
  'Четыре в ряд': 'Four in a Row',
  'Го': 'Go',
  'Сёги': 'Shogi',
  'Сянци': 'Xiangqi',
  'Легион': 'Legion',
  'Натиск': 'Onslaught',

  // ── Каталог игр: подписи (tagline) ───────────────────────────────────
  '3D детектив: вычисли убийцу': '3D whodunit: find the killer',
  '3D ракетный футбол на тачках': '3D rocket car football',
  '3D лодка из блоков против реки ловушек': '3D block boat vs. a river of traps',
  '3D шоу на вылет за короной': '3D knockout show for the crown',
  'Карты по цвету и числу': 'Match cards by color and number',
  'Показывай и угадывай слова': 'Act out and guess words',
  'Тайные роли, блеф и интуиция': 'Secret roles, bluffing and intuition',
  'Саксофоны будят, дринк спасает': 'Saxes wake you, a sip saves you',
  'Питомец, о котором заботишься': 'A pet you look after',
  'Карточная игра с чёрным юмором': 'A card game with dark humor',
  'Правда или действие': 'Truth or dare',
  'Вопросы и ответы для компании': 'Trivia questions for the group',
  'Вычисли предателя в компании': 'Spot the impostor in the group',
  'Классика за деревянным столом': 'A classic at the wooden table',
  'Классика на 90 бочонков': 'The classic 90-barrel game',
  'Кубик, змейки и лесенки': 'Dice, snakes and ladders',
  'Скупай улицы, строй империю': 'Buy up streets, build an empire',
  'Найди и потопи флот 10x10': 'Find and sink the fleet on 10×10',
  'Разбирай доску парами фишек': 'Clear the board matching pairs',
  'Переворачивай фишки соперника': "Flip your opponent's pieces",
  'Пасьянс: собери все масти': 'Solitaire: collect every suit',
  'Угадай слово по буквам': 'Guess the word letter by letter',
  'Составляй слова на доске': 'Build words on the board',
  'Найди слова в сетке букв': 'Find words in a grid of letters',
  'Съешь всё и убеги от призраков': 'Eat it all and flee the ghosts',
  'Лопай шарики по три': 'Pop bubbles in threes',
  'Аэрохоккей: первый до семи': 'Air hockey: first to seven',
  'Бильярд: восьмёрка в лузу': 'Pool: sink the 8-ball',
  'Ракетка, мяч и кирпичи': 'Paddle, ball and bricks',
  'Танковый бой с волнами врагов': 'Tank battle against enemy waves',
  'Три мини-игры под одной крышей': 'Three mini-games under one roof',
  'Японские кроссворды': 'Japanese picture crosswords',
  'Собери кубик Рубика на время': "Solve the Rubik's cube on the clock",
  'Собирай линии из шариков': 'Line up balls in a row',
  'Растолкай ящики по местам': 'Push crates into place',
  'Собери линию из четырёх': 'Line up four in a row',
  'Окружай территорию на доске': 'Surround territory on the board',
  'Японские шахматы': 'Japanese chess',
  'Китайские шахматы': 'Chinese chess',
  'Захвати мир боями на кубиках': 'Conquer the world with dice battles',
  'Стратегия захвата карты': 'A map-conquest strategy game',

  // ── Каталог игр: описания (blurb) ────────────────────────────────────
  'Социальная 3D-дедукция: один тайный Маньяк с ножом, один Шериф с единственным патроном, остальные выживают и вычисляют, кто есть кто. Соло с ботами или с друзьями по коду комнаты.':
    'Social 3D deduction: one secret Maniac with a knife, one Sheriff with a single bullet, everyone else survives and works out who is who. Solo with bots or with friends by room code.',
  'Реактивные тачки играют в футбол: буст, сальто и голы. Матч против бота или 1×1 с другом по коду комнаты.':
    'Jet-powered cars play football: boost, flips and goals. Match a bot or 1v1 a friend by room code.',
  'Строй лодку из дерева, металла и золота, запускай по неоновой реке сквозь пилы, пушки и водопад, забирай сундук с золотом. Соло или с друзьями по коду комнаты.':
    'Build a boat from wood, metal and gold, sail it down a neon river through saws, cannons and a waterfall, and grab the chest of gold. Solo or with friends by room code.',
  'Безумная 3D полоса препятствий: шестнадцать зефирок, три раунда на вылет, одна корона.':
    'A wild 3D obstacle course: sixteen marshmallows, three knockout rounds, one crown.',
  'Весёлая карточная игра про цвета и числа, в духе «Уно».':
    'A fun card game about colors and numbers, in the spirit of Uno.',
  'Игра в ассоциации, цифровой «Крокодил»: угадывай слова по подсказкам.':
    'A word-association game, digital Charades: guess words from clues.',
  'Социальная игра про доверие и обман, в духе «Мафии».':
    'A social game of trust and deception, in the spirit of Mafia.',
  'Социальный «будильник»: саксофоны нарастают, пока не докажешь глоток на камеру. Сквады, множители и лидерборд.':
    'A social “alarm clock”: the saxophones build up until you prove a sip on camera. Squads, multipliers and a leaderboard.',
  'Тёплая игра про питомца, немного как тамагочи: заботишься о зверьке, а заодно и о себе.':
    'A cozy pet game, a little like a Tamagotchi: care for the critter and for yourself along the way.',
  'Партийная карточная игра для компании: подбирай самый смешной ответ на вопрос раунда.':
    'A party card game for the group: pick the funniest answer to the round’s question.',
  'Классика вечеринок: отвечай честно или выполняй задание, три набора на любую компанию.':
    'A party classic: answer honestly or take the dare — three decks for any crowd.',
  'Соревнование эрудитов: пять тем, быстрые раунды, играй один или с друзьями.':
    'A battle of wits: five topics, fast rounds — play solo or with friends.',
  'Социальная игра: у всех одно слово, у крота другое. Вычисли, кто прикидывается.':
    'A social game: everyone shares one word, the mole has another. Work out who’s faking.',
  'Классическое домино: выкладывай кости, блокируй соперника, считай очки.':
    'Classic dominoes: lay tiles, block your opponent, count the points.',
  'Русское лото: закрывай числа на карточках, пока ведущий тянет бочонки.':
    'Russian lotto: mark the numbers on your cards as the host draws the barrels.',
  'Настольная классика: бросай кубик, лезь по лесенкам и не съезжай по змейкам.':
    'A board classic: roll the die, climb the ladders and dodge the snakes.',
  'Настольная игра про недвижимость: покупай улицы, строй дома и разоряй соперников.':
    'A real-estate board game: buy streets, build houses and bankrupt your rivals.',
  'Классический морской бой: расставь корабли и первым разгадай расстановку соперника.':
    'Classic Battleship: place your ships and be first to crack your opponent’s layout.',
  'Классический пасьянс-маджонг: снимай парные фишки и разбирай всю доску.':
    'Classic Mahjong solitaire: remove matching tiles and clear the whole board.',
  'Классика стратегии: зажимай фишки соперника и перекрашивай доску в свой цвет.':
    'A strategy classic: trap your opponent’s pieces and flip the board to your color.',
  'Классический пасьянс «Паук»: раскладывай колонны по порядку и собирай масти.':
    'Classic Spider solitaire: order the columns and build up the suits.',
  'Классическая игра в слова: открывай буквы и угадай слово раньше, чем кончатся попытки.':
    'A classic word game: reveal letters and guess the word before you run out of tries.',
  'Игра в слова на доске 15x15: выкладывай буквы, зарабатывай очки за редкие клетки.':
    'A word game on a 15×15 board: place letters and score big on rare squares.',
  'Филворд: слова спрятаны в сетке и переплетены как нитки, найди их все.':
    'A word search: words hide in the grid, woven like threads — find them all.',
  'Неоновая аркада про обжорку в лабиринте: собирай точки и уворачивайся от призраков.':
    'A neon arcade muncher in a maze: gobble the dots and dodge the ghosts.',
  'Bubble shooter: стреляй шариками, собирай тройки по цвету и очищай поле.':
    'A bubble shooter: fire bubbles, match threes by color and clear the field.',
  'Глянцевый аэрохоккей с честной физикой: отбивай шайбу и забивай до семи голов.':
    'Glossy air hockey with fair physics: knock the puck and score up to seven goals.',
  'Бильярдная «восьмёрка» с честной физикой: забей свои шары и восьмёрку последней.':
    '8-ball pool with fair physics: pot your balls, then sink the 8-ball last.',
  'Неоновая аркада: отбивай мяч ракеткой и выбивай кирпичи рикошетами.':
    'A neon arcade: bounce the ball off your paddle and smash the bricks.',
  'Аркада про танковый бой: защищай базу и отбивай волны вражеских танков.':
    'A tank-battle arcade: defend your base and fend off waves of enemy tanks.',
  'Сборник мини-игр: память, точки и спираль. Короткие партии на пару минут.':
    'A mini-game collection: memory, dots and spiral. Quick rounds of a couple minutes.',
  'Нонограммы: открывай клетки по числам и собирай картинку.':
    'Nonograms: reveal cells by the numbers and uncover the picture.',
  'Головоломка про кубик 3x3: крути грани и собери все цвета быстрее всех.':
    'A 3×3 cube puzzle: turn the faces and match every color as fast as you can.',
  'Головоломка «Lines»: двигай шарики и собирай линии по пять, пока поле не заполнилось.':
    'The Lines puzzle: move balls and form lines of five before the board fills up.',
  'Сокобан: толкай ящики на нужные места, не загнав их в угол.':
    'Sokoban: push crates onto their targets without cornering them.',
  'Логическая классика на двоих: бросай фишки в колонны и собери четыре в ряд.':
    'A two-player logic classic: drop discs into columns and get four in a row.',
  'Древняя игра Го: окружай территорию и камни соперника на доске 9x9.':
    'The ancient game of Go: surround territory and enemy stones on a 9×9 board.',
  'Японские шахматы: съеденные фигуры возвращаются в бой на твоей стороне.':
    'Japanese chess: captured pieces return to the fight on your side.',
  'Китайские шахматы: генералы, пушки и река посреди доски.':
    'Chinese chess: generals, cannons and a river across the middle of the board.',
  'Стратегия про захват мира: двигай легионы, бросай кубики и держи континенты.':
    'A world-conquest strategy: move legions, roll dice and hold the continents.',
  'Настольная стратегия: расширяй владения и выдавливай соперников с карты.':
    'A board strategy game: expand your holdings and squeeze rivals off the map.',
}
