// Каталог игр Game is Game: единый источник правды для лаунчера и бота.
// Здесь нет ни длинных тире, ни ссылок на конкретную среду, чтобы файл
// одинаково работал и на сервере (Node), и в приложении (браузер).

/** Жанр игры (для фильтров и полки категорий). */
export type Category = 'cards' | 'board' | 'party' | 'word' | 'arcade' | 'puzzle' | 'strategy'

export const CATEGORIES: { id: Category; ru: string; emoji: string }[] = [
  { id: 'cards', ru: 'Карты', emoji: '🎴' },
  { id: 'board', ru: 'Настольные', emoji: '🎲' },
  { id: 'party', ru: 'Компания', emoji: '🎉' },
  { id: 'word', ru: 'Слова', emoji: '🔤' },
  { id: 'arcade', ru: 'Аркады', emoji: '👾' },
  { id: 'puzzle', ru: 'Головоломки', emoji: '🧩' },
  { id: 'strategy', ru: 'Стратегии', emoji: '⚔️' },
]

export function categoryRu(id: Category): string {
  return CATEGORIES.find(c => c.id === id)?.ru ?? id
}

export interface GameDef {
  /** Стабильный идентификатор (используется в ссылках и аналитике). */
  id: string
  /** Название игры на русском. */
  name: string
  /** Короткая подпись под названием. */
  tagline: string
  /** Одно предложение для экрана «Об этом». */
  blurb: string
  /** Эмодзи-иконка игры. */
  emoji: string
  /** Акцентный цвет плитки (hex). */
  accent: string
  /** Тёмный акцент для нижней «губы» плитки (hex). */
  accentDeep: string
  /** @username бота игры без @. */
  bot: string
  /** Жанр для фильтров. */
  category: Category
  /** Режим: один игрок, с друзьями или и так и так. */
  players: 'solo' | 'multi' | 'both'
  /** Есть режимы с контентом 18+ (показываем метку на карточке). */
  adult?: boolean
  /** Скрыть плитку из хаба (игра остаётся валидной везде: рейтинги, квесты, ачивки). */
  hideInHub?: boolean
}

// Порядок здесь = порядок плиток в меню (флагманы первыми).
export const GAMES: GameDef[] = [
  {
    id: 'roost',
    name: 'Гнездо',
    tagline: 'Голубиная почта по живой карте мира',
    blurb: 'Отправляй настоящие письма виртуальными голубями: птица летит по карте мира в реальном времени, скорость зависит от вида и расстояния. Собирай птиц, выводи яйца, гоняй во Флаппи.',
    emoji: '🕊️',
    accent: '#97dd67',
    accentDeep: '#3f7048',
    bot: 'roostmsgbot',
    category: 'arcade',
    players: 'both',
  },
  {
    id: 'maniac',
    name: 'Маньяк',
    tagline: '3D детектив: вычисли убийцу',
    blurb: 'Социальная 3D-дедукция: один тайный Маньяк с ножом, один Шериф с единственным патроном, остальные выживают и вычисляют, кто есть кто. Соло с ботами или с друзьями по коду комнаты.',
    emoji: '🔪',
    accent: '#e0473c',
    accentDeep: '#a32718',
    bot: 'duaowdouawbot',
    category: 'party',
    players: 'both',
    hideInHub: true,
  },
  {
    id: 'nitroliga',
    name: 'Тачкобол',
    tagline: '3D ракетный футбол на тачках',
    blurb: 'Реактивные тачки играют в футбол: буст, сальто и голы. Матч против бота или 1×1 с другом по коду комнаты.',
    emoji: '🚀',
    accent: '#2f9dff',
    accentDeep: '#1560c4',
    bot: 'racketlegbot',
    category: 'arcade',
    players: 'both',
  },
  {
    id: 'warpath',
    name: 'Тропа войны',
    tagline: '3D-Risk: захвати весь мир',
    blurb: 'Настольный Риск в 3D: 42 территории на карте мира, живые кубики на физике, бонусы за континенты. Соло против ботов трёх уровней сложности или передавай телефон друзьям.',
    emoji: '🌍',
    accent: '#e0563c',
    accentDeep: '#a3311c',
    bot: 'riskrubot',
    category: 'strategy',
    players: 'both',
  },
  {
    id: 'nightline',
    name: 'Найтлайн',
    tagline: '3D ночной рынок от первого лица',
    blurb: 'Неоновый ночной рынок: ходи по докам от первого лица, делай забросы, дерись с машинами охраны и торгуй на живой бирже. Демо: деньги ненастоящие.',
    emoji: '🌃',
    accent: '#22e7ff',
    accentDeep: '#1893a8',
    bot: 'sadghsdgbot',
    category: 'arcade',
    players: 'solo',
    hideInHub: true,
  },
  {
    id: 'pomni',
    name: 'Помни',
    tagline: 'Тот, кто помнит сквозь века',
    blurb: 'Уютно-меланхоличная жизнь-RPG: ты перерождаешься сквозь перемешанное время, помнишь один, узнаёшь родные души в незнакомцах и оставляешь письма сквозь века.',
    emoji: '🕯️',
    accent: '#9b7bd4',
    accentDeep: '#5f4494',
    bot: 'theshoreofmemoriesbot',
    category: 'arcade',
    players: 'solo',
    hideInHub: true,
  },
  {
    id: 'neontide',
    name: 'Кораблик',
    tagline: '3D лодка из блоков против реки ловушек',
    blurb: 'Строй лодку из дерева, металла и золота, запускай по неоновой реке сквозь пилы, пушки и водопад, забирай сундук с золотом. Соло или с друзьями по коду комнаты.',
    emoji: '🚤',
    accent: '#66e0ff',
    accentDeep: '#1c86a8',
    bot: 'lodkabuildbot',
    category: 'arcade',
    players: 'both',
  },
  {
    id: 'chekharda',
    name: 'Чехарда',
    tagline: '3D шоу на вылет за короной',
    blurb: 'Безумная 3D полоса препятствий: шестнадцать зефирок, три раунда на вылет, одна корона.',
    emoji: '🍡',
    accent: '#ff5fa8',
    accentDeep: '#c93b7f',
    bot: 'sisiisisisididjskekejbot',
    category: 'arcade',
    players: 'multi',
  },
  {
    id: 'uno',
    name: 'Однушечка',
    tagline: 'Карты по цвету и числу',
    blurb: 'Весёлая карточная игра про цвета и числа, в духе «Уно».',
    emoji: '🎴',
    accent: '#e1554b',
    accentDeep: '#b8362c',
    bot: 'uno_gameisgame_bot',
    category: 'cards',
    players: 'both',
  },
  {
    id: 'croco',
    name: 'Крокоша',
    tagline: 'Показывай и угадывай слова',
    blurb: 'Игра в ассоциации, цифровой «Крокодил»: угадывай слова по подсказкам.',
    emoji: '🐊',
    accent: '#54b15a',
    accentDeep: '#37833f',
    bot: 'croco_gameisgame_bot',
    category: 'party',
    players: 'multi',
  },
  {
    id: 'mafia',
    name: 'Полночь',
    tagline: 'Город засыпает. Кому ты веришь?',
    blurb: 'Мафия: ночью одни тихо делают своё дело, днём весь город спорит и голосует. Роль видишь только ты.',
    emoji: '🌙',
    accent: '#6c5ce0',
    accentDeep: '#4b3bc0',
    bot: 'jdweojowedjbot',
    category: 'party',
    players: 'multi',
  },
  {
    id: 'saxalarm',
    name: 'Сакс-будильник',
    tagline: 'Саксофоны будят, дринк спасает',
    blurb: 'Социальный «будильник»: саксофоны нарастают, пока не докажешь глоток на камеру. Сквады, множители и лидерборд.',
    emoji: '🎷',
    accent: '#e0a63c',
    accentDeep: '#b47f1e',
    bot: 'qeudiuhqeuhehuqdhuebot',
    category: 'party',
    players: 'both',
    adult: true,
  },
  {
    id: 'pet',
    name: 'Шарик',
    tagline: 'Питомец, о котором заботишься',
    blurb: 'Тёплая игра про питомца, немного как тамагочи: заботишься о зверьке, а заодно и о себе.',
    emoji: '🐾',
    accent: '#f2a93b',
    accentDeep: '#d98b1f',
    bot: 'druzhok_gameisgame_bot',
    category: 'arcade',
    players: 'solo',
  },
  {
    id: 'kartishki',
    name: 'Картишки',
    tagline: 'Карточная игра с чёрным юмором',
    blurb: 'Партийная карточная игра для компании: подбирай самый смешной ответ на вопрос раунда.',
    emoji: '🃏',
    accent: '#d84a6b',
    accentDeep: '#ad2b4a',
    bot: 'doaudhouoaudhawbot',
    category: 'cards',
    players: 'multi',
    adult: true,
  },
  {
    id: 'slabo',
    name: 'Слабо?',
    tagline: 'Правда или действие',
    blurb: 'Классика вечеринок: отвечай честно или выполняй задание, три набора на любую компанию.',
    emoji: '🍾',
    accent: '#e0709b',
    accentDeep: '#c04a78',
    bot: 'ahuodwhouawhoudwahoudbot',
    category: 'party',
    players: 'multi',
    adult: true,
  },
  {
    id: 'viktorina',
    name: 'Умник',
    tagline: 'Вопросы и ответы для компании',
    blurb: 'Соревнование эрудитов: пять тем, быстрые раунды, играй один или с друзьями.',
    emoji: '🧠',
    accent: '#8a63d2',
    accentDeep: '#6c46b6',
    bot: 'aiudiuawuhiuadiwbot',
    category: 'party',
    players: 'both',
  },
  {
    id: 'krot',
    name: 'Крот',
    tagline: 'Вычисли предателя в компании',
    blurb: 'Социальная игра: у всех одно слово, у крота другое. Вычисли, кто прикидывается.',
    emoji: '🕵️',
    accent: '#8f7a4f',
    accentDeep: '#6e5c34',
    bot: 'aohudhaohdoauwbot',
    category: 'party',
    players: 'multi',
  },
  {
    id: 'domino',
    name: 'Костяшки',
    tagline: 'Классика за деревянным столом',
    blurb: 'Классическое домино: выкладывай кости, блокируй соперника, считай очки.',
    emoji: '🎲',
    accent: '#7a5c43',
    accentDeep: '#5c4230',
    bot: 'huaodhoahdououhabot',
    category: 'board',
    players: 'both',
  },
  {
    id: 'loto',
    name: 'Бочонок',
    tagline: 'Классика на 90 бочонков',
    blurb: 'Русское лото: закрывай числа на карточках, пока ведущий тянет бочонки.',
    emoji: '🎟️',
    accent: '#c98a2e',
    accentDeep: '#a56a15',
    bot: 'dh8weodhouweoudbot',
    category: 'board',
    players: 'both',
  },
  {
    id: 'lesenki',
    name: 'Лесенки',
    tagline: 'Кубик, змейки и лесенки',
    blurb: 'Настольная классика: бросай кубик, лезь по лесенкам и не съезжай по змейкам.',
    emoji: '🪜',
    accent: '#55a860',
    accentDeep: '#398245',
    bot: 'iuhqduqndqdbot',
    category: 'board',
    players: 'both',
  },
  {
    id: 'magnat',
    name: 'Магнат',
    tagline: 'Скупай улицы, строй империю',
    blurb: 'Настольная монополия в 3D: покупай улицы, строй дома и отели, разоряй соперников. Играй с ботами или друзьями онлайн.',
    emoji: '🎩',
    accent: '#d32f2f',
    accentDeep: '#a71f1f',
    bot: 'monopolyrubot',
    category: 'board',
    players: 'both',
  },
  {
    id: 'morskoyboy',
    name: 'Флотик',
    tagline: 'Найди и потопи флот 10x10',
    blurb: 'Классический морской бой: расставь корабли и первым разгадай расстановку соперника.',
    emoji: '⚓',
    accent: '#3d7fd6',
    accentDeep: '#2560b3',
    bot: 'yggyyigyibot',
    category: 'board',
    players: 'both',
  },
  {
    id: 'mahjong',
    name: 'Парочки',
    tagline: 'Разбирай доску парами фишек',
    blurb: 'Классический пасьянс-маджонг: снимай парные фишки и разбирай всю доску.',
    emoji: '🀄',
    accent: '#4aab8f',
    accentDeep: '#2f8a6e',
    bot: 'hudiwwhueduhbot',
    category: 'board',
    players: 'both',
  },
  {
    id: 'reversi',
    name: 'Перевёртыш',
    tagline: 'Переворачивай фишки соперника',
    blurb: 'Классика реверси: зажимай фишки соперника и перекрашивай доску в свой цвет.',
    emoji: '⚪',
    accent: '#4d5d75',
    accentDeep: '#36435a',
    bot: 'huwedhuweuhdbot',
    category: 'board',
    players: 'both',
  },
  {
    id: 'pauk',
    name: 'Паутинка',
    tagline: 'Пасьянс: собери все масти',
    blurb: 'Классический пасьянс «Паук»: раскладывай колонны по порядку и собирай масти.',
    emoji: '🕷️',
    accent: '#7a4fd0',
    accentDeep: '#5a34ad',
    bot: 'deoudwedbot',
    category: 'cards',
    players: 'solo',
  },
  {
    id: 'viselitsa',
    name: 'Буквоед',
    tagline: 'Угадай слово по буквам',
    blurb: 'Классическая игра в слова: открывай буквы и угадай слово раньше, чем кончатся попытки.',
    emoji: '✏️',
    accent: '#e8a23d',
    accentDeep: '#cf8417',
    bot: 'tvyhihygtgbot',
    category: 'word',
    players: 'both',
  },
  {
    id: 'bukvica',
    name: 'Буквица',
    tagline: 'Составляй слова на доске',
    blurb: 'Игра в слова на доске 15x15: выкладывай буквы, зарабатывай очки за редкие клетки.',
    emoji: '🔤',
    accent: '#d6842e',
    accentDeep: '#b26615',
    bot: 'djawjodjoiwadbot',
    category: 'word',
    players: 'both',
  },
  {
    id: 'pletenka',
    name: 'Плетёнка',
    tagline: 'Найди слова в сетке букв',
    blurb: 'Филворд: слова спрятаны в сетке и переплетены как нитки, найди их все.',
    emoji: '🧶',
    accent: '#c76a9e',
    accentDeep: '#a5477d',
    bot: 'hduauheduhbot',
    category: 'word',
    players: 'both',
  },
  {
    id: 'hrumik',
    name: 'Хрумик',
    tagline: 'Съешь всё и убеги от призраков',
    blurb: 'Неоновая аркада про обжорку в лабиринте: собирай точки и уворачивайся от призраков.',
    emoji: '👾',
    accent: '#f7b32b',
    accentDeep: '#e0941a',
    bot: 'uhdaueudeaubot',
    category: 'arcade',
    players: 'both',
  },
  {
    id: 'puzyrik',
    name: 'Пузырик',
    tagline: 'Лопай шарики по три',
    blurb: 'Bubble shooter: стреляй шариками, собирай тройки по цвету и очищай поле.',
    emoji: '🫧',
    accent: '#3fb6d9',
    accentDeep: '#2394b5',
    bot: 'hudeoudejijedbot',
    category: 'arcade',
    players: 'both',
  },
  {
    id: 'shaybus',
    name: 'Шайбус',
    tagline: 'Аэрохоккей: первый до семи',
    blurb: 'Глянцевый аэрохоккей с честной физикой: отбивай шайбу и забивай до семи голов.',
    emoji: '🏒',
    accent: '#4a90e2',
    accentDeep: '#2f6fc0',
    bot: 'ihuaediuhaeduihbot',
    category: 'arcade',
    players: 'both',
  },
  {
    id: 'duplet',
    name: 'Дуплет',
    tagline: 'Бильярд: восьмёрка в лузу',
    blurb: 'Бильярдная «восьмёрка» с честной физикой: забей свои шары и восьмёрку последней.',
    emoji: '🎱',
    accent: '#2f8f6e',
    accentDeep: '#1d6e51',
    bot: 'aouhwdouawhdhaowdbot',
    category: 'arcade',
    players: 'both',
  },
  {
    id: 'rikoshet',
    name: 'Рикошет',
    tagline: 'Ракетка, мяч и кирпичи',
    blurb: 'Неоновая аркада: отбивай мяч ракеткой и выбивай кирпичи рикошетами.',
    emoji: '🏓',
    accent: '#e2604a',
    accentDeep: '#bd402c',
    bot: 'huaeduedoubot',
    category: 'arcade',
    players: 'both',
  },
  {
    id: 'tanchiki',
    name: 'Танчики',
    tagline: 'Танковый бой с волнами врагов',
    blurb: 'Аркада про танковый бой: защищай базу и отбивай волны вражеских танков.',
    emoji: '🪖',
    accent: '#7d9b3a',
    accentDeep: '#5e7a22',
    bot: 'huaeduhuedhabot',
    category: 'arcade',
    players: 'both',
  },
  {
    id: 'zabava',
    name: 'Забава',
    tagline: 'Три мини-игры под одной крышей',
    blurb: 'Сборник мини-игр: память, точки и спираль. Короткие партии на пару минут.',
    emoji: '🎪',
    accent: '#e07f3c',
    accentDeep: '#bd6122',
    bot: 'huawuduwdubot',
    category: 'arcade',
    players: 'both',
  },
  {
    id: 'kletki',
    name: 'Клеточки',
    tagline: 'Японские кроссворды',
    blurb: 'Нонограммы: открывай клетки по числам и собирай картинку.',
    emoji: '🧩',
    accent: '#4860e6',
    accentDeep: '#3344c2',
    bot: 'dhquudbot',
    category: 'puzzle',
    players: 'both',
  },
  {
    id: 'kubik',
    name: 'Кубик',
    tagline: 'Собери кубик Рубика на время',
    blurb: 'Головоломка про кубик 3x3: крути грани и собери все цвета быстрее всех.',
    emoji: '🧊',
    accent: '#39a7c9',
    accentDeep: '#2186a6',
    bot: 'eudahuedaubot',
    category: 'puzzle',
    players: 'both',
  },
  {
    id: 'linik',
    name: 'Линик',
    tagline: 'Собирай линии из шариков',
    blurb: 'Головоломка «Lines»: двигай шарики и собирай линии по пять, пока поле не заполнилось.',
    emoji: '🔵',
    accent: '#5a7be0',
    accentDeep: '#3d5cc0',
    bot: 'deuqodebot',
    category: 'puzzle',
    players: 'both',
  },
  {
    id: 'skladik',
    name: 'Складик',
    tagline: 'Растолкай ящики по местам',
    blurb: 'Сокобан: толкай ящики на нужные места, не загнав их в угол.',
    emoji: '📦',
    accent: '#b0793a',
    accentDeep: '#8f5c22',
    bot: 'ojwedojewijobot',
    category: 'puzzle',
    players: 'both',
  },
  {
    id: 'ryad',
    name: 'Рядок',
    tagline: 'Собери линию из четырёх',
    blurb: 'Логическая классика на двоих: бросай фишки в колонны и собери четыре в ряд.',
    emoji: '🔴',
    accent: '#e05252',
    accentDeep: '#bd3535',
    bot: 'dgihdshgsddgjbot',
    category: 'strategy',
    players: 'both',
  },
  {
    id: 'go',
    name: 'Камушки',
    tagline: 'Окружай территорию на доске',
    blurb: 'Древняя игра Го: окружай территорию и камни соперника на доске 9x9.',
    emoji: '⚫',
    accent: '#5c6670',
    accentDeep: '#424b55',
    bot: 'go_gameisgame_bot',
    category: 'strategy',
    players: 'both',
  },
  {
    id: 'shogi',
    name: 'Сёгунчик',
    tagline: 'Японские шахматы',
    blurb: 'Японские шахматы: съеденные фигуры возвращаются в бой на твоей стороне.',
    emoji: '⛩️',
    accent: '#c25450',
    accentDeep: '#9e3835',
    bot: 'asfsaufasfhbot',
    category: 'strategy',
    players: 'both',
  },
  {
    id: 'xiangqi',
    name: 'Генералик',
    tagline: 'Китайские шахматы',
    blurb: 'Китайские шахматы: генералы, пушки и река посреди доски.',
    emoji: '🐉',
    accent: '#c9402e',
    accentDeep: '#a32717',
    bot: 'jackisdgjojasdjjosabot',
    category: 'strategy',
    players: 'both',
  },
  {
    id: 'legion',
    name: 'Легион',
    tagline: 'Захвати мир боями на кубиках',
    blurb: 'Стратегия про захват мира: двигай легионы, бросай кубики и держи континенты.',
    emoji: '⚔️',
    accent: '#a8552e',
    accentDeep: '#853c1a',
    bot: 'sagsdjasgsabot',
    category: 'strategy',
    players: 'both',
  },
  {
    id: 'natisk',
    name: 'Натиск',
    tagline: 'Стратегия захвата карты',
    blurb: 'Настольная стратегия: расширяй владения и выдавливай соперников с карты.',
    emoji: '🗺️',
    accent: '#6b8f3c',
    accentDeep: '#4f7024',
    bot: 'ejwdjwoedijobot',
    category: 'strategy',
    players: 'both',
  },
  {
    id: 'masterskaya',
    name: 'Мастерская',
    tagline: 'Собери свою игру за 5 минут',
    blurb: 'Конструктор мини-игр: собери тест, викторину, аркаду или питомца из шаблонов и опубликуй для всех. Внутри — игры, которые собрали другие игроки.',
    emoji: '🛠️',
    accent: '#f2a93b',
    accentDeep: '#d98b1f',
    bot: 'golubpochtabot',
    category: 'party',
    players: 'both',
  },
]

/** Прямая ссылка на Mini App игры. Открывает игру сразу, без чата с ботом. */
export function defaultLink(bot: string, startParam = 'gg'): string {
  return `https://t.me/${bot}?startapp=${encodeURIComponent(startParam)}`
}

/** Каталог со ссылками для клиента: применяет переопределения окружения, если они есть. */
export interface GameCard extends GameDef {
  link: string
}

export function buildCatalog(overrides: Record<string, { bot?: string; link?: string }> = {}): GameCard[] {
  return GAMES.filter(g => !g.hideInHub).map(g => {
    const o = overrides[g.id] ?? {}
    const bot = o.bot || g.bot
    return { ...g, bot, link: o.link || defaultLink(bot) }
  })
}
